### ISSUE TITLE
The --destination flag is mandatory even though --no-push is specified

### ISSUE THREAD

**Issue by nickdk** [GoogleContainerTools/kaniko#2185] opened 2022-07-27 14:24 UTC
**Actual behavior**

The --destination flag seems mandatory even when --no-push is specified.

**Expected behavior**

Since I just want to build a container image to a tarball it seems like I shouldn't need to specify a destination. In some cases I do want to push the tar to a container registry using Crane but that's the point where I specify the complete URI of the container image.

**To Reproduce**

(please note that I'm building locally from binary for demonstration purposes)

```
/kaniko/executor --force --context . --no-push --tarPath image.tar

WARN[0000] kaniko is being run outside of a container. This can have dangerous effects on your system
INFO[0000] Retrieving image manifest redacted
INFO[0000] Retrieving image redacted from registry redacted
INFO[0000] Built cross stage deps: map[]
INFO[0000] Retrieving image manifest redacted
INFO[0000] Returning cached image manifest
INFO[0000] Executing 0 build triggers
INFO[0000] Unpacking rootfs as cmd COPY somefile somefile requires it.
INFO[0005] COPY somefile somefile
INFO[0005] Taking snapshot of files...
error pushing image: must provide at least one destination when tarPath is specified
```

**Comment by aaron-prindle** [comment] 2023-06-22 20:25
Related:
#1613 
#1860

**Comment by aaron-prindle** [comment] 2023-06-22 20:26
I believe this is a dupe of https://github.com/GoogleContainerTools/kaniko/issues/1613, closing.

**Closed by aaron-prindle** 2023-06-22 20:26 UTC
Labels: kind/enhancement, help wanted, good first issue, priority/p2, area/cli, issue/destination
