### ISSUE TITLE
"no valid providers in chain" in Jenkins	

### ISSUE THREAD

**Issue by juanmacasau** [GoogleContainerTools/kaniko#1270] opened 2020-05-16 19:22 UTC
Im trying to use Kaniko in my Jenkinsfile: 

```
def label = "kaniko-${UUID.randomUUID().toString()}"

podTemplate(name: 'kaniko', label: label, yaml: """
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: Always
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
      - name: jenkins-docker-cfg
        mountPath: /kaniko/.docker
  volumes:
  - name: jenkins-docker-cfg
    projected:
      sources:
      - secret:
          name: regcred
          items:
            - key: .dockerconfigjson
              path: config.json
""") { 
[....]
  node(label) {  
    stage('Dockerize') {
        container(name: 'kaniko') {
            unstash 'build'
            sh 'ls'
            sh '''
            /kaniko/executor -f `pwd`/Dockerfile -c `pwd` --insecure --skip-tls-verify --cache=true --verbosity=trace --destination=index.docker.io/USERNAME/REPOSITORY:TAG
            
            '''
        }
      }
    }
```

And always I get the following error 

```
[37mDEBU[0m[0000] Copying file /home/jenkins/agent/workspace/contagio/PRO/api-sintomas-pipeline/Dockerfile to /kaniko/Dockerfile 
[37mTRAC[0m[0000] Adding /var/run to initialWhitelist     
E0516 19:12:00.571357      31 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```
 And my pipeline does not stop never. 

Somebody knows what is the problem?

Thanks!

**Comment by juanmacasau** [comment] 2020-05-24 09:56
Somebody can help me? It is for my final degree project :(

**Comment by ball-hayden** [comment] 2020-05-24 13:17
I can't be much help, but I can tell you that `while getting AWS credentials NoCredentialProviders` is likely a red-herring - your problem is likely elsewhere.
We see this in our logs all the while, and the build continues quite happily:

```
[2020-05-24T10:47:10.886Z] + /kaniko/executor --dockerfile /home/jenkins/agent/workspace/rData_GitHub_license-report_PR-1/Dockerfile --context /home/jenkins/agent/workspace/rData_GitHub_license-report_PR-1 '--cache=true' '--destination=eu.gcr.io/playerdata-infrastructure-prod/license-report:initial-report'
[2020-05-24T10:47:11.464Z] E0524 10:47:11.234842      19 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
[2020-05-24T10:47:11.465Z] 	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
[2020-05-24T10:47:11.465Z] [36mINFO[0m[0000] Resolved base name frolvlad/alpine-java:jdk8-slim to build 
[2020-05-24T10:47:11.465Z] [36mINFO[0m[0000] Using dockerignore file: /home/jenkins/agent/workspace/rData_GitHub_license-report_PR-1/.dockerignore 
[2020-05-24T10:47:11.465Z] [36mINFO[0m[0000] Retrieving image manifest frolvlad/alpine-java:jdk8-slim 
[2020-05-24T10:47:11.465Z] E0524 10:47:11.429003      19 metadata.go:154] while reading 'google-dockercfg' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg
[2020-05-24T10:47:11.465Z] E0524 10:47:11.431877      19 metadata.go:166] while reading 'google-dockercfg-url' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg-url
[2020-05-24T10:47:12.862Z] [36mINFO[0m[0001] Retrieving image manifest frolvlad/alpine-java:jdk8-slim 
[2020-05-24T10:47:13.434Z] [36mINFO[0m[0002] Retrieving image manifest adoptopenjdk:11-jre-hotspot-bionic 
[2020-05-24T10:47:14.380Z] [36mINFO[0m[0003] Retrieving image manifest adoptopenjdk:11-jre-hotspot-bionic 
[2020-05-24T10:47:14.953Z] [36mINFO[0m[0004] Built cross stage deps: map[0:[/usr/local/src/ort/scripts/import_proxy_certs.sh /usr/local/src/ort/scripts/set_gradle_proxy.sh /usr/local/src/ort/cli/build/distributions/ort-*.tar]] 
[2020-05-24T10:47:14.954Z] [36mINFO[0m[0004] Retrieving image manifest frolvlad/alpine-java:jdk8-slim 
[2020-05-24T10:47:15.895Z] [36mINFO[0m[0005] Retrieving image manifest frolvlad/alpine-java:jdk8-slim 
[2020-05-24T10:47:16.471Z] [36mINFO[0m[0005] Executing 0 build triggers                   
```

**Comment by will-darkwolf** [comment] 2020-05-29 14:44
I am also running into this issue with a gitlab-ci build running on kubernetes.

My gitlab-ci.yml job looks like:
```
kaniko:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --cache=true --dockerfile "${CI_PROJECT_DIR}/Dockerfile" --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG --context "dir://${CI_PROJECT_DIR}/"
```

**Comment by will-darkwolf** [comment] 2020-05-29 15:09
@juanmacasau 

I was able to build with this base image gcr.io/kaniko-project/executor@sha256:f652f28537fa76e8f4f9393de13a064f0206003c451ce2ad6e4359fd5a21acbc from a month ago. Not really a fix, but a workaround.

**Comment by ball-hayden** [comment] 2020-06-02 14:09
I'm also seeing this from within a GKE cluster.

We've been using kaniko in the cluster happily. This morning we enabled the workload identity feature and metadata server and kaniko now hangs as described.

**Comment by ball-hayden** [comment] 2020-06-02 15:44
In my case, this was caused by a network policy preventing access to the Google Metadata Server (`metadata.google.internal`).

Even though the network policy allowed egress on port 80, this didn't work.
Only workaround so far is to remove the egress rules from the network policy (so that any connections are allowed).

Kaniko should IMHO timeout after some (reasonably short) period when trying to get credentials.

**Comment by tejal29** [comment] 2020-08-12 23:41
duplicate of #1287

**Closed by tejal29** 2020-08-12 23:41 UTC

**Comment by DanielJonesEB** [comment] 2020-11-03 16:53
This is bonkers - why should my Kaniko build need to be able to talk to the Google Metadata Server when it's building from a Dockerfile in a directory, and outputting to a tar file?

**Comment by tejal29** [comment] 2020-11-03 22:41
we did a fix in #1445 to address checking pushing permissions when --no-push was specified. 
It unfortunately was broken in this follow up  [commit](https://github.com/GoogleContainerTools/kaniko/commit/a310cc6d1cd449f95cedd23393de766fdc649651#diff-dafa636d22231b15fa811fdcb798043e640b83c6a968fee91263d8305a406c93) 

Its fixed on master now due to 
https://github.com/GoogleContainerTools/kaniko/pull/1471

This change is pending release.

**Comment by andy-paine** [comment] 2020-11-05 10:48
I've tried building the container from HEAD and I'm still seeing some issues unfortunately. I've done a bunch of digging and I think our issue is actually just the "infinite loop" behaviour of the GCR credential package in https://github.com/vdemeester/k8s-pkg-credentialprovider as we are a) running on GCE but b) have blocked access to the metadata server as we are running untrusted workloads. I think this assumption then doesn't work for our setup https://github.com/vdemeester/k8s-pkg-credentialprovider/blob/8edca87436b8a9a0924e8c6168177cd1854bd186/gcp/metadata.go#L215. Do you think it would be reasonable to either a) not infinitely loop or b) be able to control which providers Kaniko attempts to register (rather than just relying on init functions)?

This is unrelated to the `--no-push` flag as it is about trying to authenticate with the providers for pulling images in `FROM` steps.

Thanks for looking into this!

**Comment by tejal29** [comment] 2020-11-05 16:52
Thanks @andy-paine for confirming this is related to the GCP metadata server. 
I asked internally this question and i haven't got any response yet. I will keep nudging the right ppl.

Thanks
Tejal

**Comment by tejal29** [comment] 2020-11-05 17:54
> I've tried building the container from HEAD and I'm still seeing some issues unfortunately. I've done a bunch of digging and I think our issue is actually just the "infinite loop" behaviour of the GCR credential package in https://github.com/vdemeester/k8s-pkg-credentialprovider as we are a) running on GCE but b) have blocked access to the metadata server as we are running untrusted workloads. I think this assumption then doesn't work for our setup https://github.com/vdemeester/k8s-pkg-credentialprovider/blob/8edca87436b8a9a0924e8c6168177cd1854bd186/gcp/metadata.go#L215. Do you think it would be reasonable to either a) not infinitely loop or b) be able to control which providers Kaniko attempts to register (rather than just relying on init functions)?


Thanks, i am looking to code where `k8Chains.Enabled()` is called to see if adding flags can help or disable retrying.
