### ISSUE TITLE
Regression in v0.10.0, segfaulting in util.DeleteFilesystem

### ISSUE THREAD

**Issue by leahneukirchen** [GoogleContainerTools/kaniko#705] opened 2019-06-26 12:01 UTC
**Actual behavior**

I tracked this down to commit 246cc92a33c29d76b811f7da605375d8bc4c2198:
```
INFO[0010] Saving file /srv/api/public for later use.   
INFO[0010] Deleting filesystem...                       
DEBU[0010] Not deleting /etc, as it contains a whitelisted path 
DEBU[0010] Not deleting /etc/hostname, as it's whitelisted 
DEBU[0010] Not deleting /etc/hosts, as it's whitelisted 
DEBU[0010] Not deleting /etc/mtab, as it's whitelisted  
DEBU[0010] Not deleting /etc/resolv.conf, as it's whitelisted 
DEBU[0010] Not deleting /srv, as it contains a whitelisted path 
DEBU[0010] Not deleting /srv/api, as it contains a whitelisted path 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x110c621]

goroutine 1 [running]:
github.com/GoogleContainerTools/kaniko/pkg/util.DeleteFilesystem.func1(0xc42085b5a0, 0x12, 0x0, 0x0, 0x19a12a0, 0xc4211b1950, 0x0, 0x0)
	/go/src/github.com/GoogleContainerTools/kaniko/pkg/util/fs_util.go:134 +0x51
path/filepath.walk(0xc4205431b0, 0xc, 0x19cbe60, 0xc420f3aea0, 0x18c56b8, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:377 +0x20d
path/filepath.walk(0xc420543078, 0x8, 0x19cbe60, 0xc420f3ac30, 0x18c56b8, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:381 +0x2c2
path/filepath.walk(0xc420543028, 0x4, 0x19cbe60, 0xc420f3ab60, 0x18c56b8, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:381 +0x2c2
path/filepath.walk(0x1818996, 0x1, 0x19cbe60, 0xc4209eca90, 0x18c56b8, 0x0, 0xc4200e4730)
	/usr/local/go/src/path/filepath/path.go:381 +0x2c2
path/filepath.Walk(0x1818996, 0x1, 0x18c56b8, 0x19cbe60, 0xc4209ec4e0)
	/usr/local/go/src/path/filepath/path.go:403 +0x106
github.com/GoogleContainerTools/kaniko/pkg/util.DeleteFilesystem(0xc42003ed60, 0xf)
	/go/src/github.com/GoogleContainerTools/kaniko/pkg/util/fs_util.go:132 +0x86
github.com/GoogleContainerTools/kaniko/pkg/executor.DoBuild(0x24aa780, 0x1, 0x0, 0x0, 0x1a)
	/go/src/github.com/GoogleContainerTools/kaniko/pkg/executor/build.go:495 +0x369
github.com/GoogleContainerTools/kaniko/cmd/executor/cmd.glob..func2(0x249b2a0, 0xc42054c070, 0x0, 0x7)
	/go/src/github.com/GoogleContainerTools/kaniko/cmd/executor/cmd/root.go:85 +0x7c
github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra.(*Command).execute(0x249b2a0, 0xc420038190, 0x7, 0x7, 0x249b2a0, 0xc420038190)
	/go/src/github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x249b2a0, 0x0, 0x184a841, 0x25)
	/go/src/github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra.(*Command).Execute(0x249b2a0, 0xc420513f78, 0xc4200400b8)
	/go/src/github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/go/src/github.com/GoogleContainerTools/kaniko/cmd/executor/main.go:26 +0x2d
```

**Expected behavior**

Kaniko could build this Dockerfile fine before the above commit (and in v0.9.0).

**To Reproduce**

```
docker run --rm -ti -v $PWD/api:/workspace gcr.io/kaniko-project/executor@sha256:3c820e1112b24421d103582dbf27e7fca05b4eb335adaadca3d616d3d48689b9 --dockerfile Dockerfile.minimal --context dir:///workspace/ --no-push -v debug
```

**Additional Information**

Minimal Dockerfile:

```
FROM php:alpine AS api_skeleton_php

WORKDIR /srv/api

RUN mkdir -p var/cache \
    mkdir -p /srv/api/public

VOLUME /srv/api/var

FROM nginx:alpine

WORKDIR /srv/api

COPY --from=api_skeleton_php /srv/api/public public/
```

Broken as of `gcr.io/kaniko-project/executor@sha256:3c820e1112b24421d103582dbf27e7fca05b4eb335adaadca3d616d3d48689b9`

**Comment by hobti01** [comment] 2019-08-13 09:32
Unfortunately there is no error checking in https://github.com/GoogleContainerTools/kaniko/blob/v0.10.0/pkg/util/fs_util.go#L120-L139

If there is an error, `info` is nil, causing this behaviour.
```
func DeleteFilesystem() error {
	logrus.Info("Deleting filesystem...")
	return filepath.Walk(constants.RootDir, func(path string, info os.FileInfo, _ error) error { // incoming error is ignored
		if CheckWhitelist(path) {
			if info.IsDir() { // this is nil if there was an error
				return filepath.SkipDir
			}
...
```

https://golang.org/pkg/path/filepath/#WalkFunc
> If there was a problem walking to the file or directory named by path, the incoming error will describe the problem and the function can decide how to handle that error (and Walk will not descend into that directory). In the case of an error, the info argument will be nil.

**Comment by tejal29** [comment] 2019-09-27 22:21
Thanks @leahneukirchen for detailed investigation. 
Feel free to submit a PR.

**Comment by tejal29** [comment] 2020-02-28 12:27
Thanks @leahneukirchen and @hobti01 
I added PR #1086 to return error when `filepath.Walk` sees an error.

I tried reproducing your issue  with the minimal dockerfile you mentioned on the master with "gcr.io/kaniko-project/executor:edge". I could not reproduce this.

```
/ # kaniko/executor -f dockerfiles/Dockerfile1 --context=dir://workspace --destination=gcr.io/tejal-test/test --tarPath=image.tar
INFO[0000] Resolved base name php:alpine to php:alpine  
INFO[0000] Resolved base name nginx:alpine to nginx:alpine 
INFO[0000] Using dockerignore file: /workspace/.dockerignore 
INFO[0000] Resolved base name php:alpine to php:alpine  
INFO[0000] Resolved base name nginx:alpine to nginx:alpine 
INFO[0000] Retrieving image manifest php:alpine         
INFO[0001] Retrieving image manifest php:alpine         
INFO[0002] Retrieving image manifest nginx:alpine       
INFO[0002] Retrieving image manifest nginx:alpine       
INFO[0003] Built cross stage deps: map[0:[/srv/api/public]] 
INFO[0003] Retrieving image manifest php:alpine         
INFO[0004] Retrieving image manifest php:alpine         
INFO[0004] Unpacking rootfs as cmd RUN mkdir -p var/cache     mkdir -p /srv/api/public requires it. 
INFO[0006] Taking snapshot of full filesystem...        
INFO[0007] Resolving paths                              
INFO[0007] WORKDIR /srv/api                             
INFO[0007] cmd: workdir                                 
INFO[0007] Changed working directory to /srv/api        
INFO[0007] Creating directory /srv/api                  
INFO[0007] Resolving paths                              
INFO[0007] Taking snapshot of files...                  
INFO[0007] RUN mkdir -p var/cache     mkdir -p /srv/api/public 
INFO[0007] cmd: /bin/sh                                 
INFO[0007] args: [-c mkdir -p var/cache     mkdir -p /srv/api/public] 
INFO[0007] Taking snapshot of full filesystem...        
INFO[0007] Resolving paths                              
INFO[0008] VOLUME /srv/api/var                          
INFO[0008] cmd: VOLUME                                  
INFO[0008] adding volume /srv/api/var to whitelist      
INFO[0008] Saving file /srv/api/public for later use    
INFO[0008] Deleting filesystem...                       
INFO[0008] Retrieving image manifest nginx:alpine       
INFO[0008] Retrieving image manifest nginx:alpine       
INFO[0009] Unpacking rootfs as cmd COPY --from=api_skeleton_php /srv/api/public public/ requires it. 
INFO[0010] Taking snapshot of full filesystem...        
INFO[0010] Resolving paths                              
INFO[0011] WORKDIR /srv/api                             
INFO[0011] cmd: workdir                                 
INFO[0011] Changed working directory to /srv/api        
INFO[0011] COPY --from=api_skeleton_php /srv/api/public public/ 
INFO[0011] Resolving paths                              
INFO[0011] Taking snapshot of files...

```

Can you please verify?

**Comment by tejal29** [comment] 2020-03-06 03:14
This is now fixed!

**Closed by tejal29** 2020-03-06 03:14 UTC
Labels: area/performance, fixed-needs-verfication, in progress, kind/bug, priority/p1
