### ISSUE TITLE
Kaniko executor error unpacking rootfs

### ISSUE THREAD

**Issue by cj930736** [GoogleContainerTools/kaniko#1777] opened 2021-10-19 14:00 UTC
Hello,

I am getting the following error when trying to build an image:

error building image: error building stage: failed to get filesystem from image: error removing ./etc/ssl/certs to make way for new symlink: unlinkat /etc/ssl/certs/java/cacerts: device or resource busy

The command being run is:-
sh """
					    #!/busybox/sh
                        /kaniko/executor --dockerfile Dockerfile.jvm --context `pwd` --destination <dest>
"""
Dockerfile contents:
FROM registry.access.redhat.com/ubi8/ubi-minimal:8.4 

ARG JAVA_PACKAGE=java-11-openjdk-headless
ARG RUN_JAVA_VERSION=1.3.8
ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en'
# Install java and the run-java script
# Also set up permissions for user `1001`
RUN microdnf install curl ca-certificates ${JAVA_PACKAGE} \
    && microdnf update \
    && microdnf clean all \
    && mkdir /deployments \
    && chown 1001 /deployments \
    && chmod "g+rwX" /deployments \
    && chown 1001:root /deployments \
    && curl https://repo1.maven.org/maven2/io/fabric8/run-java-sh/${RUN_JAVA_VERSION}/run-java-sh-${RUN_JAVA_VERSION}-sh.sh -o /deployments/run-java.sh \
    && chown 1001 /deployments/run-java.sh \
    && chmod 540 /deployments/run-java.sh \
    && echo "securerandom.source=file:/dev/urandom" >> /etc/alternatives/jre/conf/security/java.security

# Configure the JAVA_OPTIONS, you can add -XshowSettings:vm to also display the heap size.
ENV JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
# We make four distinct layers so if there are application changes the library layers can be re-used
COPY --chown=1001 target/quarkus-app/lib/ /deployments/lib/
COPY --chown=1001 target/quarkus-app/*.jar /deployments/
COPY --chown=1001 target/quarkus-app/app/ /deployments/app/
COPY --chown=1001 target/quarkus-app/quarkus/ /deployments/quarkus/

ENTRYPOINT [ "/deployments/run-java.sh"

**Comment by aaron-prindle** [comment] 2023-06-27 21:19
Closing as dupe of https://github.com/GoogleContainerTools/kaniko/issues/1692

**Closed by aaron-prindle** 2023-06-27 21:19 UTC
Labels: priority/p1, priority/p0, area/symlinks, works-with-docker, differs-from-docker, possible-dupe, ok-to-close?, issue/rootfs, categorized, issue/unpacking-roots
