### ISSUE TITLE
Failure while pushing large image to the registry - use of closed network connection 

### ISSUE THREAD

**Issue by bvidovic1** [GoogleContainerTools/kaniko#2470] opened 2023-04-13 21:59 UTC
**Actual behavior**
New version 1.9.2 cannot push large images to the registry. At least this is the case with Gitlab Registry.
Version 1.9.1 works.

**Expected behavior**
I would expect that image is successfully pushed - same as on 1.9.1 version.

**To Reproduce**
1. Create 4GB+ image
2. Try to push it to Gitlab registry (probably any registry is ok)

 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [x] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by bvidovic1** [comment] 2023-04-13 22:07
I see now that similar ticket that is most likely related to this issue exists: #2463

**Comment by aaron-prindle** [comment] 2023-06-25 19:44
@bvidovic1 thank you for flagging this issue and identifying this is a possible dupe of #2463.   From the issue there, it seems like a possible workaround for now would be to revert to kaniko version - `v1.9.1`.  Let me know if that works for you as a workaround here.

I'm going to close as a dupe of #2463 but feel free to continue discussion in the issue there

**Closed by aaron-prindle** 2023-06-25 19:44 UTC
