### ISSUE TITLE
Cache garbage collection

### ISSUE THREAD

**Issue by OscartGiles** [GoogleContainerTools/kaniko#2677] opened 2023-08-11 11:34 UTC
I'm trying to figure out if Kaniko runs garbage collection on its cache. 

When using a repository as a cache, my understanding is that Kaniko checks the `created` field of the config file for the cached image. If that time + the cache TTL is greater than the current time, the cache entry is not used:

https://github.com/GoogleContainerTools/kaniko/blob/73b711816e07054f3fe5d9016a30f2c25110c56e/pkg/cache/cache.go#L93-L100

However, I can't see that the entry is ever deleted from the repository by Kaniko. 

Does the manifest of cache entry ever get removed or does the cache just grow indefinitely?

**Comment by aaron-prindle** [comment] 2023-08-11 20:46
@OscartGiles, currently kaniko does not run garbage collection on the cache.  A potential short term workaround would be to use something like `https://cloud.google.com/artifact-registry/docs/repositories/cleanup-policy` if your registry supports this (some kind of cron job that reaps the cache)

**Comment by aaron-prindle** [comment] 2023-08-11 20:47
Going to close this as a dupe of https://github.com/GoogleContainerTools/kaniko/issues/998.  Feel free to continue the thread there and/or upvote the thread there

**Closed by aaron-prindle** 2023-08-11 20:47 UTC
