### ISSUE TITLE
I use insecure-skip-tls-verify flag, but also get connection refused error

### ISSUE THREAD

**Issue by StephenLiuYa** [GoogleContainerTools/kaniko#200] opened 2018-06-06 12:10 UTC
time="2018-06-06T09:59:29Z" level=error msg="Get https://XXX/v2/: dial tcp XXX:443: connect: connection refused"

**Comment by priyawadhwa** [comment] 2018-06-06 16:29
Hey @StephenLiuYa , this is being worked on in #169

**Comment by priyawadhwa** [comment] 2018-06-11 17:26
Closing as dupe of #168

**Closed by priyawadhwa** 2018-06-11 17:26 UTC
