### ISSUE TITLE
False-positive cache-hit on COPY --from

### ISSUE THREAD

**Issue by haizaar** [GoogleContainerTools/kaniko#870] opened 2019-11-20 06:31 UTC
**Actual behavior**
I have a two stage docker image that first build sphinx docs and then copies it to the second nginx image:
```dockerfile
FROM python:3.7.5-alpine3.10 AS builder
RUN apk add --no-cache build-base libxml2-dev libxslt-dev graphviz
COPY requirements.txt /
RUN pip install --upgrade -r /requirements.txt
WORKDIR /build
COPY . ./
RUN make html
########################
FROM nginx:1.17.5-alpine AS runner
COPY --from=builder /build/_build/html /usr/share/nginx/html
```

I build it on Google Cloud Build using `gcr.io/kaniko-project/executor:latest` builder. 

The problem is the last copy instruction - even through generated HTML files differ from the previously built revision, kaniko still prefers to use the cached version:
```
Step #0: build succeeded.
Step #0:
Step #0: The HTML pages are in _build/html.
Step #0:
Step #0: Build finished. The HTML pages are in _build/html.
Step #0: INFO[0062] Taking snapshot of full filesystem...
Step #0: INFO[0064] Pushing layer gcr.io/xxx/docs-server/cache:cd602b7af9c972414b3241eb3a192a606755174cf665f9806155078915975932 to cache now
Step #0: INFO[0068] Saving file /build/_build/html for later use.
Step #0: INFO[0068] Deleting filesystem...
Step #0: INFO[0068] Downloading base image nginx:1.17.5-alpine
Step #0: INFO[0069] Error while retrieving image from cache: getting file info: stat /cache/sha256:b4c0378c841cd76f0b75bc63454bfc6fe194a5220d4eab0d75963bccdbc327ff: no such file or directory
Step #0: INFO[0069] Downloading base image nginx:1.17.5-alpine
Step #0: INFO[0069] Checking for cached layer gcr.io/xxx/docs-server/cache:5de22bf6a7763f10cd0ffa0592b8f51c876286a1d0f50564cf2f21bfd6262dc4...
Step #0: INFO[0069] Using caching version of cmd: COPY --from=builder /build/_build/html /usr/share/nginx/html
Step #0: INFO[0069] Skipping unpacking as no commands require it.
Step #0: INFO[0069] Taking snapshot of full filesystem...
Step #0: INFO[0070] COPY --from=builder /build/_build/html /usr/share/nginx/html
Step #0: INFO[0070] Found cached layer, extracting to filesystem
```

**Expected behavior**
Detect that stage 0 image files' have changes and discard cache for `COPY --from` directive in the stage 1.

**To Reproduce**
1. Run:
```sh
mkdir /tmp/bug; cd /tmp/bug
python3.7 -mvenv /tmp/bug-env && source /tmp/bug-env/bin/activate
mkdir docs
echo 'Sphinx==2.2.1' >> docs/requirements.txt
pip install -r docs/requirements.txt
cd docs
echo no | sphinx-quickstart -p foo -a foo -v 0.0.1 -r 0.0.1 -l en
```
Then add the above Dockerfile under `docs/`.

2. Now add it all to git, commit and trigger Cloud Build using the following step:
```yaml
steps:
  - name: gcr.io/kaniko-project/executor:latest
    args:
      - --cache=true
      - --cache-ttl=336h  # 2 weeks
      - --context=/workspace/docs
      - --dockerfile=/workspace/docs/Dockerfile
      - --destination=gcr.io/$PROJECT_ID/docs-server:$BRANCH_NAME-$COMMIT_SHA
```
3. Change `docs/index.rst`, commit, trigger new build and see that resulting images still has the old version of the docs

**Additional Information**
 - Dockerfile - see above
 - Build Context - see above
 - Kaniko Image sha256:9c40a04cf1bc9d886f7f000e0b7fa5300c31c89e2ad001e97eeeecdce9f07a29
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [x] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [x] </li></ul>|

**Comment by stroncium** [comment] 2019-11-20 15:48
I can confirm this problem.

**Comment by mcfedr** [comment] 2019-11-25 13:44
Just found this having the exact same issue using kaniko on cloud build. will try suggested work aorund/roll back.

**Comment by cvgw** [comment] 2019-11-26 01:14
this appears to the same underlying problem as #845 and #589

**Comment by mcfedr** [comment] 2019-12-02 12:52
@cvgw Any movement on getting that fix merged?

**Comment by cvgw** [comment] 2019-12-02 22:17
@mcfedr hoping to get merged this week

**Comment by kzap** [comment] 2019-12-10 07:39
I can also confirm this does not exist in `0.13.0` but not sure why
hope the fixes can get merged soon

**Comment by cvgw** [comment] 2019-12-10 17:23
Once https://github.com/GoogleContainerTools/kaniko/issues/899 is fixed this issue should be resolved

**Comment by cvgw** [comment] 2019-12-17 00:19
This should be fixed as of master@https://github.com/GoogleContainerTools/kaniko/commit/a675098b452d020bf678063a3ac2d3be84b0e545

Some assistance verifying that it is fixed would be appreciated. Thank you

**Comment by mcfedr** [comment] 2019-12-17 08:15
> This should be fixed as of master@[a675098](https://github.com/GoogleContainerTools/kaniko/commit/a675098b452d020bf678063a3ac2d3be84b0e545)
> 
> Some assistance verifying that it is fixed would be appreciated. Thank you

Is there a prebuilt image from master that I can test with? it looks like `gcr.io/kaniko-project/executor:latest` is fixed at the last release

**Comment by fredr** [comment] 2019-12-17 08:27
@mcfedr I think you can use the git hash, like `gcr.io/kaniko-project/executor:a675098b452d020bf678063a3ac2d3be84b0e545`

**Comment by edbighead** [comment] 2019-12-17 08:46
@mcfedr you can check image versions in GCR https://console.cloud.google.com/gcr/images/kaniko-project/GLOBAL/executor?gcrImageListsize=30

**Comment by edbighead** [comment] 2019-12-17 09:13
> This should be fixed as of master@[a675098](https://github.com/GoogleContainerTools/kaniko/commit/a675098b452d020bf678063a3ac2d3be84b0e545)
> 
> Some assistance verifying that it is fixed would be appreciated. Thank you

@cvgw fix is working on the latest version for me.
`INFO[0390] No cached layer found for cmd COPY --from=build /usr/src/app/target/app-0.0.1.jar /home/user/app.jar`

**Comment by toxsick** [comment] 2019-12-17 09:54
@cvgw works for me too. Thanks!

**Comment by cvgw** [comment] 2019-12-17 16:33
Thanks everyone for the help solving and verifying this issue. Closing, but feel free to reopen if it isn't 100% fixed

**Closed by cvgw** 2019-12-17 16:33 UTC
Labels: area/caching, kind/bug, priority/p2

**Comment by stroncium** [comment] 2019-12-17 19:27
Any info on when release version lands(0.15.0?)? (I can test commit based version, but won't be able to use non-release version in production.)

**Comment by cvgw** [comment] 2019-12-17 20:41
@stroncium plan is to release v0.15.0 this week

**Comment by jamil-s** [comment] 2021-04-19 21:15
Hey folks, we're seeing the same issue on the most recent `debug` build. In a multi-stage build, the first layer generates a new image and yet the second layer still results to the cached version, not sure if there's been a regression in this

**Comment by DXCanas** [comment] 2021-05-08 00:43
Also seeing this in `latest`

**Comment by KasnocknDave** [comment] 2021-07-20 06:49
Also seeing this in 1.6, examples described here https://github.com/GoogleContainerTools/kaniko/issues/1348 as well.
