### ISSUE TITLE
Why is --destination flag needed when using --no-push flag?

### ISSUE THREAD

**Issue by Mo0rBy** [GoogleContainerTools/kaniko#2629] opened 2023-07-19 09:12 UTC
**Actual behavior**
When building an image with Kaniko using the `--no-push` flag, it still errors and demands that the `--destination` flag must be used.

**Expected behavior**
If the `--no-push` flag is used, you don't want to push to a registry, so why is the `--destination` flag a required argument??

Unless I'm misunderstanding something, a destination should not be needed when using the `--no-push` flag.

**To Reproduce**
1. Setup the kaniko-executor:debug image
2. /kaniko/executor \
    --context ${DOCKERFILE_PATH} \
    --dockerfile Dockerfile \
    --no-push \                                            -> Not pushing to any registry
    --destination ${aRegistryAddress} \.  -> Why is this needed if I'm not pushing??
    --tar-path ${imageTarFile}                   -> I am saving the image instead of pushing
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [x] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by Mo0rBy** [comment] 2023-08-16 18:02
Could this be a duplicate of #1613 ?? Was looking at the plan for the next release and noticed it on the list.

**Comment by aaron-prindle** [comment] 2023-08-16 18:15
`--destination` is not required when the `--no-push` flag is used but it is currently required when the `--tar-path` flag is used (even if the --no-push flag is also used) which is the case in the kaniko params posted in this issue.  Going to close this as a dupe of #1613, thanks for flagging this

**Closed by aaron-prindle** 2023-08-16 18:15 UTC
Labels: kind/bug, kind/enhancement, priority/p2
