### ISSUE TITLE
Cannot push to gcr.io with recent kaniko executor > 0.1.0

### ISSUE THREAD

**Issue by berndtj** [GoogleContainerTools/kaniko#392] opened 2018-10-11 17:33 UTC
**Actual behavior**

Cannot push images as part of a knative build when configured to push to gcr.io and using a kaniko executor > 0.1.0 (I have tried 0.3 -> latest).  The same build completes successfully when using 0.1.0 *or* pushing to a different repository (i.e. dockerhub).  The issue comes down to authentication.

```
error pushing image: failed to push to destination gcr.io/dispatch-193801/2a20fe50-ee26-4ad5-b595-ba8aa18788c5:latest: DENIED: "Access denied."
```

**Expected behavior**

Image can be pushed to gcr.io or any registry with suitable credentials.

**To Reproduce**

I don't know how to reproduce this in a very isolated manor.  I've included a script which demonstrates the issue using knative build.  This script is basically the same as the following tutorial:

https://github.com/GoogleCloudPlatform/knative-build-tutorials/tree/master/docker-build

See attached script.
[bug.sh.txt](https://github.com/GoogleContainerTools/kaniko/files/2469994/bug.sh.txt)

This has also been reported as an issue in knative:

https://github.com/knative/build/issues/414

**Additional Information**
 - Dockerfile 
   Please provide either the Dockerfile you're trying to build or one that can reproduce this error.
 - Build Context
   Please provide or clearly describe any files needed to build the Dockerfile (ADD/COPY commands)
 - Kaniko Image (fully qualified with digest)

**Comment by gaoning777** [comment] 2018-10-13 00:13
same here. The kaniko images v0.4.0 and latest cannot push to another registry even though the service account are authorized with storage admin permission.

**Comment by peter-evans** [comment] 2018-10-21 06:28
@berndtj I'm unable to reproduce this. I followed the steps at the link below to create a new cluster and install Istio and Knative.
https://github.com/knative/docs/blob/master/install/Knative-with-GKE.md

I then followed the tutorial you referenced and was able to build and push the image with both `executor:v0.1.0` and `executor:v0.5.0`.
https://github.com/GoogleCloudPlatform/knative-build-tutorials/tree/master/docker-build

Perhaps you could try the same steps to create a cluster from scratch and see if you still see the issue.

**Comment by priyawadhwa** [comment] 2018-11-16 22:38
@berndtj are you still seeing this issue?

**Comment by berndtj** [comment] 2018-11-16 22:40
I have not tried in quite some time.  If no one else is reporting the issue, go ahead and close it.

**Comment by priyawadhwa** [comment] 2018-11-16 23:07
Thanks for the quick response! @gaoning777 are you still seeing this issue?

**Comment by davidkopp** [comment] 2018-12-09 21:31
I still have the same problem: Pushing to gcr.io fails if the kaniko executor version is above v0.1.0.
I tested all available releases (v0.2.0 - v0.6.0) but only v0.1.0 works.

Like @berndtj I also followed the steps described in [https://github.com/GoogleCloudPlatform/knative-build-tutorials/tree/master/docker-build](https://github.com/GoogleCloudPlatform/knative-build-tutorials/tree/master/docker-build).

**Comment by mattmoor** [comment] 2019-01-17 18:50
Sounds like this is still an issue, so reopening.

cc interested parties @dlorenc @evankanderson @jonjohnsonjr

**Comment by evankanderson** [comment] 2019-01-18 20:16
Based on the debugging in https://github.com/knative/build/issues/450#issuecomment-437116252, it looks like Kaniko no longer uses the `~/.docker/config.json` file to find credential helpers and their arguments. Would it be possible to bring back this functionality as a flag?

**Comment by dlorenc** [comment] 2019-01-22 23:15
Fixed with https://github.com/knative/build-templates/pull/87

**Closed by dlorenc** 2019-01-22 23:15 UTC

**Comment by SeriyBg** [comment] 2019-06-29 15:05
I'm experiencing this issue as well. What is the solution to overcome this issue??

**Comment by usamadanish22** [comment] 2021-01-01 13:57
Facing the same issue.

**Comment by xclud** [comment] 2021-04-28 11:19
Same issue here in Kaniko version 1.5.x and 1.6.0. I run Kaniko in Tekton.
