### ISSUE TITLE
Don't overwrite tag flag.

### ISSUE THREAD

**Issue by kfox1111** [GoogleContainerTools/kaniko#1736] opened 2021-09-09 18:02 UTC
It would be useful if there was a flag to tell Kaniko to fail the build if the image already exists in the registry with the specified tag. This would help protect immutable images from accidentally getting overwritten.

**Comment by aaron-prindle** [comment] 2023-06-12 23:03
Closing as dupe of #2015

**Closed by aaron-prindle** 2023-06-12 23:03 UTC
Labels: kind/feature-request, priority/p3, area/registry, feat/tagging
