### ISSUE TITLE
Build an image from kaniko using kaniko fails

### ISSUE THREAD

**Issue by saidrebhi** [GoogleContainerTools/kaniko#1183] opened 2020-04-07 23:06 UTC
I am trying to build an image using kaniko from this Dockerfile:
```
FROM golang:1.13 AS build 
WORKDIR /project
COPY . .
RUN env GOOS=linux GOARCH=386 CGO_ENABLED=0 go build -mod=vendor -o bin/project ./cmd/project/main.go

FROM gcr.io/kaniko-project/executor:debug-v0.19.0 AS final
COPY --from=build /project/bin/project /kaniko/project
ENTRYPOINT ["/kaniko/project"]
```

But it fails and I see the error below:
`
error building image: error building stage: failed to get filesystem from image: removing whiteout kaniko/.docker/.wh..wh..opq: unlinkat /kaniko/.docker/.wh..opq: read-only file system
2020/04/07 21:41:10 deleting temp file "/kaniko/repo" : err = <nil>`

Any thoughts on how to solve this please?

**Comment by tomprince** [comment] 2020-04-14 22:42
This is a duplicate of #1136.

**Comment by tejal29** [comment] 2020-05-07 18:36
closing as dupe

**Closed by tejal29** 2020-05-07 18:36 UTC
