### ISSUE TITLE
/tmp permissions broken in some subset of multi-stage builds

### ISSUE THREAD

**Issue by mothershipper** [GoogleContainerTools/kaniko#1176] opened 2020-04-04 00:12 UTC
**Actual behavior**
I have a multi-stage build using nodejs/yarn. When I install and run yarn in the second stage, the resulting `/tmp` folder under a `docker run` has the following permissions 

```bash
node@2355092d5f0f:/usr/src/app$ ls -la /tmp/
total 12
drwxr-xr-x 1 root root 4096 Apr  3 22:58 .
drwxr-xr-x 1 root root 4096 Apr  3 22:58 ..
drwxr-xr-x 1 root root 4096 Apr  3 22:58 v8-compile-cache-0
```
Even stranger is that these permissions seem correct at every point in the build, here's the last step before `CMD`:

```bash
INFO[0034] RUN echo "tmp permissions - after user switch" && ls -la /tmp
INFO[0034] cmd: /bin/sh
INFO[0034] args: [-c echo "tmp permissions - after user switch" && ls -la /tmp]
tmp permissions - after user switch
total 12
drwxrwxrwt 3 root root 4096 Apr  4 00:08 .
drwxr-xr-x 1 root root 4096 Apr  4 00:08 ..
drwxr-xr-x 3 root root 4096 Apr  4 00:08 v8-compile-cache-0
```

Just the resulting image has the permission flags wrong for `/tmp`

**Expected behavior**

When I build the same image using Docker, the `/tmp` folder is left alone:

```bash
node@194d8cf3afd1:/usr/src/app$ ls -la /tmp/
total 20
drwxrwxrwt 1 root root 4096 Mar 31 03:27 .
drwxr-xr-x 1 root root 4096 Apr  3 22:59 ..
drwxr-xr-x 1 root root 4096 Mar 31 03:27 v8-compile-cache-0
```

**To Reproduce**

Full Repro:

https://github.com/mothership/kaniko-issue-repro

```
# builds, pushes the image to a registry of your choosing, and pulls it back down
make test-kaniko TEST_REPO=myregistry/myimage 
# does a docker run --entrypoint bash on the test image
make debug-kaniko 
```
You should be able to pull those images as well and inspect them locally.

**Additional Information**
- This only seems to affect multi-stage builds, when I collapse both stages into a single stage the issue goes away
- [Yarn is already installed in the base image](https://github.com/nodejs/docker-node/blob/e76dc47a4104a1b06765673dadb56f1855c32cad/12/stretch-slim/Dockerfile#L59-L91) (`node:12.16.1-slim`), this repro installs the exact same version over it, but we noticed it when we tried to upgrade yarn
- Best we can tell, this isn't specific to `yarn`, but we've not been able to find any other way to reproduce.
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [x] </li></ul>|

**Comment by mothershipper** [comment] 2020-04-04 18:38
Just realized the linked repository was private, I've fixed that

**Comment by Jeiwan** [comment] 2020-04-06 04:07
We're also having this bug but we're using a single-stage build. We're getting it in our production image in 100% of cases, thus it's not flaky. But it's hard to say what causes it exactly. We're using several dependency managers in the image (yarn being one of them) and the bug happens only when all of them are used.
I couldn't make a minimal Dockerfile that reproduces the bug because all steps from our production image seem to be needed for it to happen.


> these permissions seem correct at every point in the build

We're also seeing this. The permissions are changed after image is built.

**Comment by gilbsgilbs** [comment] 2020-04-06 18:27
I think this might be related to #1163 . You can try against #1166 to see if it fixes your issue.

**Comment by tejal29** [comment] 2020-05-08 01:41
@mothershipper This is now fixed on master and latest kaniko release!

![Uploading proof.png…]()

Please re-open if you this issue again.

**Closed by tejal29** 2020-05-08 01:41 UTC
Labels: area/multi-stage builds, fixed-needs-verfication

**Comment by mothershipper** [comment] 2020-05-08 20:29
Thanks @tejal29 and @gilbsgilbs, confirmed that 0.22.0 fixes the issue in our repro repository.

**Comment by Jeiwan** [comment] 2020-05-12 04:22
It works for us too, thanks!
