### ISSUE TITLE
Snapshot occurs but no push when attempting to push to Harbor repo

### ISSUE THREAD

**Issue by rpete3** [GoogleContainerTools/kaniko#1887] opened 2022-01-20 06:09 UTC
**Actual behavior**
I have tried nearly every combination of config and I am unable to push to harbor. There is no error message after the snapshot, even with debug verbosity, it just ends. 

**Expected behavior**
Push to harbor
**To Reproduce**
1. ...build image with kaniko destination is a harbor repo

**Additional Information**
 - Dockerfile 
   Please provide either the Dockerfile you're trying to build or one that can reproduce this error.
 - Build Context
   Please provide or clearly describe any files needed to build the Dockerfile (ADD/COPY commands)
 - Kaniko Image (fully qualified with digest)
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by aaron-prindle** [comment] 2023-06-22 22:42
Dupe of #2414, closing

**Comment by aaron-prindle** [comment] 2023-06-22 22:43
@rpete3

**Closed by aaron-prindle** 2023-06-22 22:43 UTC
Labels: priority/p2, area/errorhandling, area/registry, kind/friction
