### ISSUE TITLE
Push to local Docker

### ISSUE THREAD

**Issue by abergmeier** [GoogleContainerTools/kaniko#885] opened 2019-11-26 10:14 UTC
GCB currently does not fully support Kaniko (things like `images`). Their handling seems to hardcoded to Docker "internals".
As such, it would be really good if Kaniko had an option to besides pushing to a remote to also write the produced image to local Docker.

**Comment by aaron-prindle** [comment] 2023-05-29 01:47
Closing as dupe of #1331 (there is more discussion/info there so closing this one even though it is older)

**Closed by aaron-prindle** 2023-05-29 01:47 UTC
Labels: kind/enhancement, priority/p2, area/registry, platform/cloud-build
