### ISSUE TITLE
Checking Kaniko version

### ISSUE THREAD

**Issue by BenHizak** [GoogleContainerTools/kaniko#741] opened 2019-08-16 23:13 UTC
Is it possible to check which version of Kaniko I'm running?

I'd expect something like
```docker run --rm -it --entrypoint=/busybox/bash gcr.io/kaniko-project/executor:debug kaniko --version```

**Comment by tejal29** [comment] 2019-09-27 21:23
closing as dupe of #772

**Closed by tejal29** 2019-09-27 21:23 UTC
