### ISSUE TITLE
Building from a multi-arch image unpacks wrong architecture image

### ISSUE THREAD

**Issue by jesusofsuburbia** [GoogleContainerTools/kaniko#182] opened 2018-05-15 14:25 UTC
Hi again,

another issue that I noticed while testing with kaniko and gitlab:

When building a project and the Dockerfile build `FROM` a multi-arch image,
the image that is pulled and unpacked is not matching the system architecture.

Tested with an `arm` device:

When I have `FROM alpine:3.7` (which is multi-arch and supports arm) in my dockerfile, it fails (exec format error)

Using `FROM arm32v6/alpine:3.7` instead works.

(btw: Kaniko itself runs perfectly on arm!)

This would be a nice feature!
It would also make sense to annotate the manifest correctly when pushing.

super cool stuff, thank you!

**Comment by priyawadhwa** [comment] 2018-05-15 16:50
Would you be able to provide the Dockerfile you're trying to build and logs of the error? We have an integration test which pulls alpine:3.7 and is passing, so the error might be coming from some command in the Dockerfile which isn't being handled correctly.

**Comment by priyawadhwa** [comment] 2018-05-21 22:18
Hey @jesusofsuburbia -- I was able to build an image with both `alpine:3.7` and `arm32v6/alpine:3.7` on a standard Kubernetes cluster, but we don't plan on supporting any other architectures at this time.

**Comment by priyawadhwa** [comment] 2018-05-23 18:22
I'm going to go ahead and close this issue, please open another if you have any more questions!

**Closed by priyawadhwa** 2018-05-23 18:22 UTC

**Comment by everflux** [comment] 2019-02-02 23:10
I have the same problem with a ARM64 kubernetes cluster using CRI-O runtime and a multi-stage dockerfile for building, build is controlled by kaniko.

I use a custom image for the first stage, then switch to nginx and get an exec format error.

```
FROM registry.docker-registry:31000/angular-cli:latest AS ngcli
....
FROM nginx:alpine AS app
COPY --from=ngcli /app/dist/demo /usr/share/nginx/html/
COPY nginx/default.conf /etc/nginx/conf.d/default.conf.template
RUN chown -R nginx /etc/nginx

COPY nginx/start.sh /start.sh
CMD ["/start.sh"]
```

The nginx:alpine image on dockerhub is a multiarch manifest, arm64 beeing available.

**Comment by everflux** [comment] 2019-02-03 09:47
I suspect this is might be caused by https://github.com/GoogleContainerTools/kaniko/issues/535 - when specifying the exact image (without :latest or any other tag!), the build works:

```
FROM docker.io/library/nginx@sha256:3e495e5de0023ec106254479c4a683fce191592a33bb24e88649c362c86ecd02
```
But this is obviously not the desired behaviour for multi-arch images.
The nginx manifest refers to images that have both tags and hashes as identifier.

**Comment by jonjohnsonjr** [comment] 2019-04-17 22:49
@everflux I added a `WithPlatform` option in the library that kaniko is using: https://github.com/google/go-containerregistry/pull/408

You could use that [here](https://github.com/GoogleContainerTools/kaniko/blob/378a3f9573561f87b582524467be98a62848edf2/pkg/util/image_util.go#L1260) and passing in a [`Platform`](https://github.com/google/go-containerregistry/blob/1d38b9cfdb9d294aca666bf0c1c0bcade771e8c9/pkg/v1/platform.go#L18) based on the current [runtime](https://golang.org/pkg/runtime/) would make that work.

It's unclear to me if that should always happen or be based on some flag.

**Comment by lisa** [comment] 2019-04-27 14:24
I ran into this as well, and have opened https://github.com/GoogleContainerTools/kaniko/pull/646 in the kaniko project.

This, however, is more widespread than just kaniko. For example, https://github.com/google/ko also [ends up calling image.Remote](https://github.com/google/ko/blob/7c4a93a7178374153cbfba6a1002a7afb856078c/pkg/commands/config.go#L37-L44). Any project that doesn't use the `WithPlatform` option will hit this behaviour.

**Comment by jonjohnsonjr** [comment] 2019-04-29 17:40
At last for `ko`, using the current platform is almost always going to be the wrong thing for e.g. anyone using macOS, since AFAIK there isn't a way to run kubernetes on a mac, though I agree this could definitely be handled better.
