### ISSUE TITLE
reproducible cause panic

### ISSUE THREAD

**Issue by Gnoale** [GoogleContainerTools/kaniko#2537] opened 2023-05-29 12:49 UTC
Trying to build an image with the `--reproducible` flag causes a panic in v 1.10

It seems to happen only after the  latest step of the build

```
...
INFO[0022] Found cached layer, extracting to filesystem 
INFO[0048] COPY cmd cmd                                 
INFO[0048] Taking snapshot of files...                  
INFO[0049] COPY pkg pkg                                 
INFO[0049] Taking snapshot of files...                  
panic: runtime error: index out of range [23] with length 23

goroutine 1 [running]:
github.com/google/go-containerregistry/pkg/v1/mutate.Time({0x1d88d30, 0xc000496c00}, {0xc000496b80?, 0xc00063b800?, 0x0?})
        /src/vendor/github.com/google/go-containerregistry/pkg/v1/mutate/mutate.go:405 +0x9db
github.com/google/go-containerregistry/pkg/v1/mutate.Canonical({0x1d88d30?, 0xc000496c00?})
        /src/vendor/github.com/google/go-containerregistry/pkg/v1/mutate/mutate.go:509 +0x2d
github.com/GoogleContainerTools/kaniko/pkg/executor.DoBuild(0x29b1820)
        /src/pkg/executor/build.go:715 +0xee5
github.com/GoogleContainerTools/kaniko/cmd/executor/cmd.glob..func2(0x299c600?, {0x1960c3a?, 0xb?, 0xb?})
        /src/cmd/executor/cmd/root.go:163 +0x1c7
github.com/spf13/cobra.(*Command).execute(0x299c600, {0xc000000190, 0xb, 0xb})
        /src/vendor/github.com/spf13/cobra/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x299c600)
        /src/vendor/github.com/spf13/cobra/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(0x196d7bd?)
        /src/vendor/github.com/spf13/cobra/command.go:992 +0x19
main.main()
        /src/cmd/executor/main.go:31 +0x6c
```

**Comment by sumkincpp** [comment] 2023-05-29 14:39
The problem is relevant to https://github.com/google/go-containerregistry, you can try proposing bugfix there

**Comment by aaron-prindle** [comment] 2023-05-29 20:42
This is the relevant bug in go-containerregistry:

https://github.com/google/go-containerregistry/issues/1646

**Comment by aaron-prindle** [comment] 2023-05-30 22:29
Fix PR merged upstream - https://github.com/google/go-containerregistry/pull/1715

**Closed** 2023-06-07 22:59 UTC
Labels: kind/bug, area/behavior, priority/p0, area/cli, feature/reproducible-digest
