### ISSUE TITLE
multistage binary not found

### ISSUE THREAD

**Issue by matti** [GoogleContainerTools/kaniko#577] opened 2019-02-22 10:24 UTC
```
FROM golang as builder

RUN go get github.com/mholt/caddy/caddy
RUN go get github.com/caddyserver/builds

WORKDIR /$GOPATH/src/github.com/mholt/caddy/caddy
RUN go run build.go
RUN chmod +x caddy
RUN mv caddy /caddy

#-----
FROM ubuntu:18.04
COPY --from=builder /caddy /usr/local/bin

ENTRYPOINT [ "caddy" ]
```

`caddy` is not in `/usr/local/bin` -- this works when built with docker

**Comment by dlorenc** [comment] 2019-02-28 21:43
I'm unable to reproduce this. Could you attach full logs and show how you're invoking Kaniko?

**Comment by dlorenc** [comment] 2019-03-06 18:46
I'm going to close this for now. Please reopen with more details if you can.

**Closed by dlorenc** 2019-03-06 18:46 UTC
