### ISSUE TITLE
The .dockerignore file also matches between stages

### ISSUE THREAD

**Issue by michas2** [GoogleContainerTools/kaniko#595] opened 2019-03-04 02:44 UTC
**Actual behavior**
The patterns in `.dockerignore` match not only in workdir but also when copying between stages.

**Expected behavior**
I expected kaniko to have the same semantics as in `docker build`.
The patterns should match only on initial import relative to `/workdir/` not between stages relative to `/`.

**To Reproduce**

```
$ cat Dockerfile 
from busybox
run mkdir /foo/
run touch /foo/bar
run ls -l / /foo/

from busybox
copy --from=0 /foo/ /foo/
run ls -l / /foo/
$ cat .dockerignore 
/foo/
$ docker run --rm -v $PWD:/workspace gcr.io/kaniko-project/executor:v0.9.0 --no-push
[...]
INFO[0007] copy --from=0 /foo/ /foo/                    
INFO[0007] Taking snapshot of full filesystem...        
INFO[0007] Skipping paths under /kaniko, as it is a whitelisted directory 
INFO[0007] Skipping paths under /dev, as it is a whitelisted directory 
INFO[0007] Skipping paths under /proc, as it is a whitelisted directory 
INFO[0007] Skipping paths under /sys, as it is a whitelisted directory 
INFO[0007] Skipping paths under /workspace, as it is a whitelisted directory 
INFO[0008] No files were changed, appending empty layer to config. No layer added to image. 
INFO[0008] run ls -l / /foo/                            
INFO[0008] cmd: /bin/sh                                 
INFO[0008] args: [-c ls -l / /foo/]                     
ls: /foo/: No such file or directory
```
Trying the same with v0.7.0 or `docker build` works fine.

**Comment by MajorBreakfast** [comment] 2019-04-02 07:48
I ran into the same issue. Here's my minimal test scenario

Dockerfile:
```dockerfile
FROM alpine:3.9 AS intermediate

RUN cd /
RUN mkdir myDir
RUN echo "I am here!!!" > /myDir/shouldBeCopied.txt

FROM alpine:3.9

COPY --from=intermediate /myDir/shouldBeCopied.txt wasCopied.txt

RUN cat wasCopied.txt
```

Dockerignore:
```gitignore
# Each one prevents shouldBeCopied.txt from being copied (remove all these to make it work)
/myDir/shouldBeCopied.txt
/myDir
myDir

# Weirdly not a problem
shouldBeCopied.txt
```

```bash
docker run -v ${PWD}:/project gcr.io/kaniko-project/executor:debug-c8fabdf6e43b19f6a223f1d0b06e127d0774bd7e executor --context project --dockerfile ./project/Dockerfile --no-push
```

Expected output: Log message "I am here!!!" contained in the build log

**Comment by heroic** [comment] 2019-04-23 16:53
We got this issue today as well. node_modules from the first step would not get copied to the next as long as it was present in .dockerignore

**Comment by davidcurrie** [comment] 2019-04-30 13:19
Hitting this too. Particularly problematic if, like me, your `.dockerignore` typically starts with a `**` followed by a whitelist.

**Comment by leosunmo** [comment] 2019-05-20 02:01
Hit the same issue as @heroic with `node_modules` not being copied between build steps.
As far as I can tell this seems like the common pattern for front-end builds that utilise multiple build steps (which is more and more common as you don't want all that initial build bloat in the final image) and the `node_modules` directory seems a common target to ignore. Unsure what the best workaround is for now but we've decided to remove `.dockerignore` completely and try to rely on Kaniko as much as possible.

**Comment by thewilli** [comment] 2019-07-15 10:27
> @leosunmo Unsure what the best workaround is for now but we've decided to remove .dockerignore completely and try to rely on Kaniko as much as possible.

For sure not the *best* workaround, but I went with using the `executor:debug` image to have a shell and then alter / remove the `.dockerignore` without any persistent changes to the repository in the corresponding CI step only.

**Comment by i-wilson** [comment] 2019-07-31 00:35
I ended up getting around this the same way @thewilli

I'd love to actually help fix this, Is the logic simple between how docker cli handles this vs kaniko? I'll dig around but if someone could point me in the right direction I'd appreciate it.

**Comment by tejal29** [comment] 2020-02-04 23:40
thanks all. i have a fix for this and will try to get this in by next release.

**Comment by nnatter** [comment] 2020-02-13 17:17
that are great news - thanks a lot! @tejal29

**Comment by afirth** [comment] 2020-03-09 14:52
@tejal29 is this fixed now? I noticed that `.dockerignore` doesn't seem to work at all in 0.16.0, but it's back in 0.18.0 - couldn't find anything in the release notes though

**Comment by tejal29** [comment] 2020-03-11 17:53
@afirth no i have not merged the patch. i will get it in v0.19.0

**Comment by glen-84** [comment] 2020-03-18 18:49
@tejal29 Did you forget about this? 😞

**Comment by malmuzaini** [comment] 2020-03-30 14:58
The issue is still exist in version 0.19.0!!

**Comment by eonicle** [comment] 2020-04-16 14:22
Just hit that issue for a first time - pretty frustrating. If real fix is delayed, this should at least be mentioned somewhere in docs.

**Comment by tejal29** [comment] 2020-05-06 04:29
Sorry folks, this got dropped. Fix here ->  https://github.com/GoogleContainerTools/kaniko/pull/1234

**Closed** 2020-05-19 22:40 UTC
Labels: area/dockerfile-command, in progress, priority/p1
