### ISSUE TITLE
Error: error resolving dockerfile path: copying dockerfile: creating file: open /kaniko/Dockerfile: permission denied

### ISSUE THREAD

**Issue by yashcodecollab** [GoogleContainerTools/kaniko#1363] opened 2020-07-29 16:57 UTC
Hi I am still running into the same issue. Is there a resolution for this @tejal29

Error: error resolving dockerfile path: copying dockerfile: creating file: open /kaniko/Dockerfile: permission denied

**Comment by tejal29** [comment] 2020-08-12 18:46
@yashcodecollab please specify `--context=pathMounted/` and `-f` dockerfile as path relative to `pathMounted`

Does that make sense?
Please see examples in `README`

**Comment by TBBle** [comment] 2020-08-13 09:41
I think I just bounced off this same issue, I'm passing `--context` to point to a subdirectory of the CWD (a self-contained Docker context) but it's using the Dockerfile from CWD, which then fails because it references files that aren't in the context. `-f` doesn't appear in the README.md that I can see, so I'm confused by this solution. The [README.md does say](https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
> kaniko's build context is very similar to the build context you would send your Docker daemon for an image build; it represents a directory containing a Dockerfile which kaniko will use to build your image.

But it's clearly pulling the Dockerfile from CWD, not `--context`.

Should I be using `--context-sub-path`? Or will that still make the full `--context` tree available to the builder?

**Comment by adhikasp** [comment] 2020-12-03 04:27
I got this exact same error 
> Error: error resolving dockerfile path: copying dockerfile: creating file: open /kaniko/Dockerfile: permission denied

The problem in my case was I am trying to run the kaniko container under non-root user. After changing back to root, it run fine.

**Comment by ttfreeman** [comment] 2021-04-27 21:33
@adhikasp Kaniko is supposed to work with non-root user.

**Comment by TBBle** [comment] 2021-04-28 13:32
Internally, [Kaniko copies the given Dockerfile to `/kaniko/Dockerfile`](https://github.com/GoogleContainerTools/kaniko/blob/a0c96b4edcaeee437243484f5880833518d06551/cmd/executor/cmd/root.go#L258-L272), so it can only work with a non-root user, if the non-root user has permission to write to `/kaniko`.

So either the container in question was faulty and `/kaniko` is supposed to be world-writeable, or the kaniko container needs to be run as either root, or a specific UID that owns `/kaniko`.

**Comment by lvarin** [comment] 2022-01-25 12:11
I am suffering from this problem as well. The only user/UID than can write in `/kaniko` and run kaniko is `root`/`0`:

```
/kaniko $ ls -alh
total 110M   
drwxr-xr-x    1 0        0           4.0K Apr 26  2021 .
drwxr-xr-x    1 0        0           4.0K Jan 25 11:42 ..
```

And this folder is a constant (If I read the code correctly:):

https://github.com/GoogleContainerTools/kaniko/blob/main/pkg/constants/constants.go#L31

**Comment by luidoc** [comment] 2022-02-11 18:27
Hi I am still running into the same issue. Is there a resolution for this, running the kaniko container under non-root user.
../executor --dockerfile=Dockerfile --context=/kaniko/buildcontext --no-push
Error: error resolving dockerfile path: copying dockerfile: creating file: open /kaniko/Dockerfile: permission denied

[](https://github.com/GoogleContainerTools/kaniko/blob/a0c96b4edcaeee437243484f5880833518d06551/cmd/executor/cmd/root.go#L258-L272)

opts.DockerfilePath = constants.DockerfilePath
DockerfilePath = "/kaniko/Dockerfile"

**Comment by imjasonh** [comment] 2022-02-11 19:20
Basically, kaniko expects to run as root inside the container. There are a bunch of things that don't work as expected if that's not satisfied, including apparently this.

**Comment by very-doge-wow** [comment] 2022-03-09 14:17
So what exactly is supposed to be the solution to this problem? As far as my understanding goes, kaniko was supposed to work without root privileges. I believe making the constant mentioned by @lvarin configurable would solve the issue, as users then could configure their own paths which ARE writable by non-root users.

**Comment by imjasonh** [comment] 2022-03-09 14:30
> So what exactly is supposed to be the solution to this problem?

The solution to the problem is for someone to investigate this issue and fix it. It could even be you! 😄 

This has also been requested in https://github.com/GoogleContainerTools/kaniko/issues/1945, and as far as I know it should be possible. My main concern would be testing this path well end-to-end, since I wouldn't be surprised if there are lots of corners of the code that subtly assume `/kaniko` is the reserved directory.

**Comment by imjasonh** [comment] 2022-03-09 16:53
> A solution for this ticket might be to simply change the Dockerfiles so that /kaniko is writable by all users.

That seems like an easy and worthwhile change. If someone sends me a PR I'll approve it 👍

**Comment by vvatlin** [comment] 2022-06-24 15:56
Still have the same issue

**Closed** 2022-06-27 20:45 UTC
Labels: kind/question
