### ISSUE TITLE
Can't use some images from registry.opensuse.org

### ISSUE THREAD

**Issue by svalo** [GoogleContainerTools/kaniko#368] opened 2018-09-27 09:25 UTC
**Actual behavior**
Trying to use registry.opensuse.org/suse/templates/images/sle-12-sp3/base/images/sle12:sp3 image inside a gitlab pipeline leads to the following error
```
INFO[0001] Downloading base image registry.opensuse.org/suse/templates/images/sle-12-sp3/base/images/sle12:sp3 
2018/09/19 09:22:25 No matching credentials were found, falling back on anonymous
error building image: getting stage builder for stage 0: DIGEST_INVALID: ""
```
I get the same error if I try to use kaniko  from my desktop.

I can pull the failing image using docker command.

**Expected behavior**
The build successfully execute

**To Reproduce**
1. Create a folder and `cd` into it
2. Create a dockerfile with a single line "FROM  registry.opensuse.org/suse/templates/images/sle-12-sp3/base/images/sle12:sp3"
3. Run the command `sudo docker run -v $PWD:/workspace -it --rm gcr.io/kaniko-project/executor:debug -f Dockerfile --no-push -c /workspace/`
4. Error received
```
INFO[0001] Downloading base image registry.opensuse.org/suse/templates/images/sle-12-sp3/base/images/sle12:sp3 
2018/09/19 09:22:25 No matching credentials were found, falling back on anonymous
error building image: getting stage builder for stage 0: DIGEST_INVALID: ""
```

**Additional Information**
 - Kaniko Image: gcr.io/kaniko-project/executor@sha256:ba44aa3e45a440184b81d639088e6d3af5da3b403a7628c0679b43ee79847e6b

- Registry is reachable at following url https://registry.opensuse.org/cgi-bin/cooverview

- The image from the opensuse registry has only one layer and has multiple architecture

- I can succesfully use the image `registry.opensuse.org/suse/templates/images/sle-12-sp3/containers/my_container:latest` log for this run is:
```
sudo docker run -v $PWD:/workspace -it --rm gcr.io/kaniko-project/executor:debug -f Dockerfile --no-push -c /workspace/
INFO[0000] Downloading base image registry.opensuse.org/suse/templates/images/sle-12-sp3/containers/my_container:latest 
2018/09/27 08:51:09 No matching credentials were found, falling back on anonymous
INFO[0000] Executing 0 build triggers                   
INFO[0000] Extracting layer 0                           
INFO[0024] Extracting layer 1                           
INFO[0024] Extracting layer 2                           
INFO[0025] Extracting layer 3                           
INFO[0025] Taking snapshot of full filesystem...        
INFO[0026] Skipping push to container registry due to --no-push flag 
```
This image has only one arch and has multiple layers, the first layer of the image is the same layer of the failing image

To reproduce change the `FROM` line in the Dockerfile with `registry.opensuse.org/suse/templates/images/sle-12-sp3/containers/my_container:latest` 

- Other images which fail:
 - registry.opensuse.org/suse/templates/images/sle-15/base/images/suse/sle15:current
 - registry.opensuse.org/virtualization/containers/images/opensuse-leap-42.3/containers/opensuse/leap:42.3
 - registry.opensuse.org/suse/templates/images/sle-15/base/images/sle15:sp0

- Other image which succeed:
 - registry.opensuse.org/virtualization/appliances/images/images/opensuse/dice:latest

The image `registry.opensuse.org/suse/templates/images/sle-15/containers/my_container:latest` fails with a different error:
```
INFO[0000] Downloading base image registry.opensuse.org/suse/templates/images/sle-15/containers/my_container:latest 
2018/09/27 09:06:59 No matching credentials were found, falling back on anonymous
INFO[0000] Executing 0 build triggers                   
INFO[0000] Extracting layer 0                           
INFO[0031] Extracting layer 1                           
INFO[0031] Extracting layer 2                           
error building image: error building stage: removing whiteout etc/repos_obs_dockersupport.d/.wh..wh..opq: lstat /etc/repos_obs_dockersupport.d/.wh..opq: operation not permitted
```

But it gets past the stage of extracting the base image

I'd be happy to provide more details if needed and I'm available for debugging

**Comment by mlschroe** [comment] 2018-09-27 11:33
It gets the tag data which contains a fat manifest. Then it tries to fetch the sub-manifest via a request to "blobs" instead of "manifests", that's why our registry responds with an "UNKNOWN_BLOB" error.

I added a workaround so that the registry allows fetching a manifest over the "blobs" route, but this should IMHO be fixed in kaniko as well.

**Comment by mlschroe** [comment] 2018-09-27 11:48
OTOH does kaniko even support fat manifests (aka manifest lists)?

**Comment by svalo** [comment] 2018-09-27 14:14
Don't know if it can help to narrow down the issue but if I manually call `curl  https://registry.opensuse.org/v2/suse/templates/images/sle-12-sp3/base/images/sle12/manifests/sp3` and use the digest of the correct architecture as the `FROM` line  I can successfully use kaniko with the image.

```
curl  https://registry.opensuse.org/v2/suse/templates/images/sle-12-sp3/base/images/sle12/manifests/sp3

{
   "schemaVersion" : 2,
   "mediaType" : "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests" : [
      {
         "mediaType" : "application/vnd.docker.image.manifest.v2+json",
         "size" : 538,
         "digest" : "sha256:8e6be753499a9a453348ade8e94fb455ffd9a42c54a463654a02c8325a83a8ff",
         "platform" : {
            "architecture" : "arm64",
            "os" : "linux"
         }
      },
      {
         "mediaType" : "application/vnd.docker.image.manifest.v2+json",
         "size" : 538,
         "digest" : "sha256:6af35803dbc71d8f2155011bc00bcaea39a378490d46b1d0f9c2eab60b4fca1f",
         "platform" : {
            "architecture" : "ppc64le",
            "os" : "linux"
         }
      },
      {
         "mediaType" : "application/vnd.docker.image.manifest.v2+json",
         "size" : 538,
         "digest" : "sha256:aee08869d7c1ac4ee6eba99db4b97ecfd742a07b9ce0080e4fa6014bd197e713",
         "platform" : {
            "architecture" : "s390x",
            "os" : "linux"
         }
      },
      {
         "mediaType" : "application/vnd.docker.image.manifest.v2+json",
         "size" : 538,
         "digest" : "sha256:81c6dcdba669145fab791136976d1d0172054045bf7e19d3e9a7beffca049ddd",
         "platform" : {
            "architecture" : "amd64",
            "os" : "linux"
         }
      }
   ]
}
```
I then use the digest from the `amd64` arch in the `FROM` line which become:

`FROM registry.opensuse.org/suse/templates/images/sle-12-sp3/base/images/sle12@sha256:81c6dcdba669145fab791136976d1d0172054045bf7e19d3e9a7beffca049ddd`

and as a result I get:
```
sudo docker run -v $PWD:/workspace -it --rm gcr.io/kaniko-project/executor:debug -f Dockerfile --no-push -c /workspace/
INFO[0000] Downloading base image registry.opensuse.org/suse/templates/images/sle-12-sp3/base/images/sle12@sha256:81c6dcdba669145fab791136976d1d0172054045bf7e19d3e9a7beffca049ddd 
2018/09/27 14:12:45 No matching credentials were found, falling back on anonymous
INFO[0001] Extracting layer 0                           
INFO[0026] Taking snapshot of full filesystem...        
INFO[0028] Skipping push to container registry due to --no-push flag 
```

**Comment by vielmetti** [comment] 2018-12-12 20:20
From a first look, the problem appears to be somewhere in this function

https://github.com/GoogleContainerTools/kaniko/blob/master/pkg/cache/cache.go#L42

That in turn points me at what looks like this related issue in the underlying library.

https://github.com/google/go-containerregistry/issues/119

**Comment by jonjohnsonjr** [comment] 2019-03-06 21:40
This should be fixed once https://github.com/google/go-containerregistry/pull/398 merges.

**Comment by tejal29** [comment] 2019-09-20 18:48
We pull in the go-container library dependency which has the fix for  google/go-containerregistry#398 
@svalo can you verify if your issue is fixed?

**Comment by svalo** [comment] 2019-10-29 16:20
@tejal29 Excuse me for my lateness.

After @mlschroe  comment https://github.com/GoogleContainerTools/kaniko/issues/368#issuecomment-425056931 I was able to pull the image so I did not have any other failure.

Maybe we can ask them to undo what they did and check if it works now. 

Here what happens when I run the steps from my original comment

`sudo docker run -v $PWD:/workspace -it --rm gcr.io/kaniko-project/executor:debug -f Dockerfile --no-push -c /workspace/`

I pulled `executor:debug` few minutes ago and image id is `63f723c122a5`

My `Dockerfile` is the following:
```
FROM registry.opensuse.org/suse/templates/images/sle-12-sp3/base/images/sle12:sp3
RUN ls -al /
```
Output: 
```
 sudo docker run -v $PWD:/workspace -it --rm gcr.io/kaniko-project/executor:debug -f Dockerfile --no-push -c /workspace/                                                                            
INFO[0000] Resolved base name registry.opensuse.org/suse/templates/images/sle-12-sp3/base/images/sle12:sp3 to registry.opensuse.org/suse/templates/images/sle-12-sp3/base/images/sle12:sp3                                                                                                                                                                                                   
INFO[0000] Resolved base name registry.opensuse.org/suse/templates/images/sle-12-sp3/base/images/sle12:sp3 to registry.opensuse.org/suse/templates/images/sle-12-sp3/base/images/sle12:sp3                                                                                                                                                                                                   
INFO[0000] Downloading base image registry.opensuse.org/suse/templates/images/sle-12-sp3/base/images/sle12:sp3                                                                                                                                                                                                                                                                               
INFO[0000] Error while retrieving image from cache: getting file info: stat /cache/sha256:ce216add53cfb862ffbc71e45d77b579700a290a6ec8733617dfa206d9fafafb: no such file or directory                                                                                                                                                                                                        
INFO[0000] Downloading base image registry.opensuse.org/suse/templates/images/sle-12-sp3/base/images/sle12:sp3                                                                                                                                                                                                                                                                               
INFO[0000] Built cross stage deps: map[]                                                                                                                                                      
INFO[0000] Downloading base image registry.opensuse.org/suse/templates/images/sle-12-sp3/base/images/sle12:sp3                                                                                                     
INFO[0001] Error while retrieving image from cache: getting file info: stat /cache/sha256:ce216add53cfb862ffbc71e45d77b579700a290a6ec8733617dfa206d9fafafb: no such file or directory                                                                                                                                                                                                        
INFO[0001] Downloading base image registry.opensuse.org/suse/templates/images/sle-12-sp3/base/images/sle12:sp3                                                                                                                                                                                                                                                                               
INFO[0001] Unpacking rootfs as cmd RUN ls -al / requires it.                                                                                                                                  
INFO[0025] Taking snapshot of full filesystem...                                                                                                                                              
INFO[0026] RUN ls -al /                                                                                                                                                                       
INFO[0026] cmd: /bin/sh                                                                                  
INFO[0026] args: [-c ls -al /]                                                                           
total 88                                                                                                 
drwxr-xr-x   1 root root  4096 Oct 29 16:03 .                                                            
drwxr-xr-x   1 root root  4096 Oct 29 16:03 ..   
-rwxr-xr-x   1 root root     0 Oct 29 16:03 .dockerenv                                                                                  
drwxr-xr-x   2 root root  4096 Oct 29 16:03 bin                                                          
drwxr-xr-x   2 root root 12288 Oct 29 16:03 busybox                                                                                     
drwxr-xr-x   5 root root   360 Oct 29 16:03 dev                                                                                         
drwxr-xr-x   1 root root  4096 Oct 29 16:03 etc                                                                                                                                                                    
drwxr-xr-x   2 root root  4096 Oct 29 16:03 home                    
drwxr-xr-x   1 root root  4096 Oct 29 16:03 kaniko                                                                                      
drwxr-xr-x   6 root root  4096 Oct 29 16:03 lib                     
drwxr-xr-x   5 root root  4096 Oct 29 16:03 lib64                   
drwxr-xr-x   2 root root  4096 Oct 29 16:03 mnt                                                                                                                                                                                                                                 
drwxr-xr-x   2 root root  4096 Oct 29 16:03 opt                                                                                                               
dr-xr-xr-x 255 root root     0 Oct 29 16:03 proc                                                                                                              
drwx------   4 root root  4096 Oct 29 16:03 root                                                                                                              
drwxr-xr-x   9 root root  4096 Oct 29 16:03 run                                                                                                               
drwxr-xr-x   2 root root  4096 Oct 29 16:03 sbin                               
drwxr-xr-x   2 root root  4096 Oct 29 16:03 selinux                            
drwxr-xr-x   4 root root  4096 Oct 29 16:03 srv                                                                                                               
dr-xr-xr-x  13 root root     0 Oct 29 16:03 sys                                
drwxrwxrwt   2 root root  4096 Oct 29 16:03 tmp                                
drwxr-xr-x  13 root root  4096 Oct 29 16:03 usr                                                                                                                                                                                                                                                                              
drwxr-xr-x  11 root root  4096 Oct 29 16:03 var                                                
drwxr-xr-x   2 1000 1000  4096 Oct 29 16:03 workspace                                                                                                                                         
INFO[0026] Taking snapshot of full filesystem...                                                                                                                                              
INFO[0026] No files were changed, appending empty layer to config. No layer added to image.                                                                                                   
INFO[0026] Skipping push to container registry due to --no-push flag 
```

If I run the same command with kaniko image  `cadbf60105c9`from 13 month ago it successfully pulls the image and lists the directories

**Comment by cvgw** [comment] 2019-11-22 17:01
I've verified that this issue has been fixed. If this is a mistake and the issue is still present please feel free to re-open this issue.

**Closed by cvgw** 2019-11-22 17:01 UTC
Labels: area/registry, kind/bug, priority/awaiting_evidence
