### ISSUE TITLE
Question: does kaniko confirmedly support Docker Content Trust?

### ISSUE THREAD

**Issue by RoFz** [GoogleContainerTools/kaniko#2258] opened 2022-09-20 14:16 UTC
Hello all,

this is a follow-up of #1575: can kaniko sign and push images to a container registry in the same fashion as docker cli does? Just looking for a confirmation before evaluating alternate paths.

Cheers

**Comment by aaron-prindle** [comment] 2023-06-12 22:58
Currently this is not supported directly in kaniko.  There is currently discussion around adding this support but nothing in our current roadmap and it likely will not happen in the short term.  From the issue you linked, there is info on how to use cosign + kaniko to sing images:

https://github.com/GoogleContainerTools/kaniko/issues/1575#issuecomment-1075502795
I would recommend signing images built with Kaniko using [cosign](https://github.com/sigstore/cosign), after the build is complete, then verifying it before pulling+running it.

Going to close this a dupe of #1575 as that issue asks a similar question

**Closed by aaron-prindle** 2023-06-12 22:58 UTC
