### ISSUE TITLE
images on registry are bigger with kaniko

### ISSUE THREAD

**Issue by muecahit94** [GoogleContainerTools/kaniko#1698] opened 2021-07-13 13:49 UTC
Hi, we are moving our build process to Kaniko, but on the registry we see different sizes when we push the images with docker or with kaniko. 
On the server the images have the same size, but on the registry the image pushed from kaniko is about 15% bigger than when its build and pushed by docker.

Is it an issue/bug or is it known and normal?

**Comment by calebwoofenden** [comment] 2022-05-19 20:40
Did you ever find out anything more about this? I am seeing the same thing. I also see other discrepancies between the same Dockerfile built with `docker build` versus built with kaniko.

**Comment by muecahit94** [comment] 2022-05-20 07:54
@calebwoofenden unfortunately I couldnt find anything more. I just accepted that the images are bigger with kaniko, I just hope they will optimize the imagesize it in the feature

**Comment by aaron-prindle** [comment] 2023-06-14 17:13
Closing as dupe of https://github.com/GoogleContainerTools/kaniko/issues/2261

**Closed by aaron-prindle** 2023-06-14 17:13 UTC
