### ISSUE TITLE
Is there a way to get metrics of kaniko for different aspects like building and pushing image

### ISSUE THREAD

**Issue by pagarwal-tibco** [GoogleContainerTools/kaniko#1815] opened 2021-11-09 15:41 UTC
**Additional Information**
We are passing following arguments to kaniko
`
--dockerfile=/context/Dockerfile --context=dir://workspace
--cache=true --cache-dir=/cache --snapshotMode=redo --single-snapshot
--destination=<tag1>
--destination=<tag2>
`
 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>Yes</li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by aaron-prindle** [comment] 2023-05-30 19:48
Dupe of https://github.com/GoogleContainerTools/kaniko/issues/2493, closing this issue even though older as that issue has more context

**Closed by aaron-prindle** 2023-05-30 19:48 UTC
Labels: kind/feature-request, priority/p3, possible-dupe
