### ISSUE TITLE
repository name with port

### ISSUE THREAD

**Issue by david6102** [GoogleContainerTools/kaniko#2396] opened 2023-02-16 07:15 UTC
I used kaniko to push images to my Harbor registry, but it returned an error like this:

error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: getting tag for destination: repository can only contain the characters `abcdefghijklmnopqrstuvwxyz0123456789_-./`: /my.project.com:8080/mypro/test.

Does it occur due to Harbor runs with port 8080? How can I slove it?

**Comment by aaron-prindle** [comment] 2023-05-29 07:45
I believe this is a dupe of https://github.com/GoogleContainerTools/kaniko/issues/2414.  The comment below on that issue mentions a way of authenticated to Harbor:
https://github.com/GoogleContainerTools/kaniko/issues/2414#issuecomment-1489467535

Closing this issue, feel free to continue the discussion in https://github.com/GoogleContainerTools/kaniko/issues/2414

**Closed by aaron-prindle** 2023-05-29 07:45 UTC
