### ISSUE TITLE
Resolve paths does not resolve correctly for paths with "/"

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/kaniko#1112] opened 2020-03-06 17:40 UTC
A GCB user reported this bug, 

```
FROM node:lts-slim
WORKDIR /var/www/ <-- THIS TRAILING SLASH 

```

resulted into this error

```
error building image: error building stage: failed to take snapshot: unable to add file /var/www/build/build to layered map: error creating hash for /var/www/build/build: lstat /var/www/build/build: no such file or directory
```

**Comment by gilbsgilbs** [comment] 2020-03-06 17:56
This is a duplicate of #1109

**Closed** 2020-03-06 18:20 UTC
Labels: regression
