### ISSUE TITLE
COPY not creating relative workdir directories

### ISSUE THREAD

**Issue by jpatterson-fastly** [GoogleContainerTools/kaniko#1352] opened 2020-07-17 02:31 UTC
**Actual behavior**
Somewhere between 0.14.0 and latest, behaviour has changed with copying files into relative directories which need to be created within the WORKDIR, eg, if I have this dockerfile, I expect that `bin/` would be created within the WORKDIR, and the file placed into this path (other tools successfully create the relative directory, and place file inside, and did so before 0.14 of Kaniko):
```
FROM ubuntu:latest
WORKDIR /build
COPY podinfo.yaml bin/
RUN ls -la /build/bin
```

What happens now is that file.yaml gets created in /build as a file named `bin`:

Output from Kaniko on the above Dockerflle:
```
INFO[0000] Retrieving image manifest ubuntu:latest
INFO[0003] Retrieving image manifest ubuntu:latest
INFO[0007] Built cross stage deps: map[]
INFO[0007] Retrieving image manifest ubuntu:latest
INFO[0011] Retrieving image manifest ubuntu:latest
INFO[0015] Executing 0 build triggers
INFO[0015] Unpacking rootfs as cmd COPY podinfo.yaml bin/ requires it.
INFO[0023] WORKDIR /build
INFO[0023] cmd: workdir
INFO[0023] Changed working directory to /build
INFO[0023] Creating directory /build
INFO[0023] Taking snapshot of files...
INFO[0023] COPY podinfo.yaml bin/
INFO[0023] Taking snapshot of files...
INFO[0023] RUN ls -la /build/bin
INFO[0023] Taking snapshot of full filesystem...
INFO[0023] cmd: /bin/sh
INFO[0023] args: [-c ls -la /build/bin]
INFO[0023] Running: [/bin/sh -c ls -la /build/bin]
-rw-r--r-- 1 root root 986 Jul 17 02:21 /build/bin
INFO[0023] Taking snapshot of full filesystem...
INFO[0023] No files were changed, appending empty layer to config. No layer added to image.
INFO[0023] Skipping push to container registry due to --no-push flag
```

**Expected behavior**

Expect that /build/bin/podinfo.yaml gets created, not /build/bin <-- as a file

Output from Docker:
```
docker build -f Dockerfile /tmp                                                                                                                                      
Sending build context to Docker daemon  3.119kB
Step 1/4 : FROM ubuntu:latest
 ---> adafef2e596e
Step 2/4 : WORKDIR /build
 ---> Using cache
 ---> 4d06377069b1
Step 3/4 : COPY podinfo.yaml bin/
 ---> e81b9ce0f562
Step 4/4 : RUN ls -l /build/bin
 ---> Running in 36534a5d62c9
total 4
-rw-r--r-- 1 root root 986 Jul 15 04:47 podinfo.yaml
Removing intermediate container 36534a5d62c9
 ---> 808ca51a1ba4
Successfully built 808ca51a1ba4
```

This successfully works if a fullpath is provided as the COPY dstpath, eg. `COPY podinfo.yml /build/bin`, guessing the dstpath is being cleaned and is having its `/` stripped, making kaniko think its a dst file, not a dir.
Can someone please let me know if this is the expected behaviour these days, and a full path is required as the COPY dst path?

**Comment by hpdvanwyk** [comment] 2020-07-17 10:24
We see something similar.

Our dockerfile has something like
```
WORKDIR somewhere
COPY --from=BUILD_IMAGE foo/shell-main/target/lib ./lib
```
Attempting to pull the resulting image results in
```
failed to register layer: Error processing tar file(exit status 1): link /somewhere/lib /somewhere/lib: no such file or directory
```
Doing something like
```
COPY --from=BUILD_IMAGE foo/shell-main/target/lib /somewhere/lib
```
creates a working image.

**Comment by RaveNoX** [comment] 2020-07-20 18:03
Looks like problem in WORKDIR handling, because have similar problem, but with RUN after WORKDIR

**Comment by tejal29** [comment] 2020-08-12 21:44
Looks like the bug is here 
https://github.com/GoogleContainerTools/kaniko/blob/c480a063475e2b0af66214af4c065fc6000f36a3/pkg/util/command_util.go#L185

Instead of using `filepath.join` we can replace this with 
```
strings.Join([]string{cwd, newDest}, pathSeparator)
```

**Comment by tejal29** [comment] 2020-08-12 21:44
Would you be up for submitting a pr?

**Comment by JeromeJu** [comment] 2023-08-22 14:35
Thanks for the pointers @tejal29 . 
It seems that the fix suggested at using strings.Join to circumvent the Clean function in filepath.Join. I opened #2695 as an attempt to fix.
But when I look at https://pkg.go.dev/path/filepath#Clean:~:text=func-,Clean,-%C2%B6, I wonder if it does solve this case with having `/build/bin/podinfo.yaml`?

**Comment by JeromeJu** [comment] 2023-08-22 21:51
Thanks to the guidance and checkin on this issue @aaron-prindle .

This can be confirmed that could not be no longer reproduced and from the [existing codebase at main ](https://github.com/GoogleContainerTools/kaniko/blob/3f99717c509558eb079f3299bbb3d451a5288877/pkg/util/command_util.go#L188) as of [v1.14.0](https://github.com/GoogleContainerTools/kaniko/releases/tag/v1.14.0).

Closing for now.

**Closed by JeromeJu** 2023-08-22 21:51 UTC
Labels: kind/bug, help wanted, cmd/copy, easy-fix, priority/p1, regression, works-with-docker, differs-from-docker, fix-suggested, cmd/workdir, categorized, regression/0.14.0

**Comment by aaron-prindle** [comment] 2023-08-22 22:04
Adding some info from the attempted repro that showed kaniko @ HEAD seems to work for this now:

`Dockerfile`
```
```

`docker build`
```
aprindle@aprindle-ssd ~/kaniko-ctx-dir docker build . --no-cache
Sending build context to Docker daemon   2.56kB
Step 1/5 : FROM ubuntu:latest
 ---> 01f29b872827
Step 2/5 : WORKDIR /build
 ---> Running in 501672fd1f7d
Removing intermediate container 501672fd1f7d
 ---> 559716044153
Step 3/5 : RUN pwd
 ---> Running in 38c693e977b7
/build
Removing intermediate container 38c693e977b7
 ---> 80d1b6ffc3c0
Step 4/5 : COPY podinfo.yaml bin/
 ---> d5b961fcf322
Step 5/5 : RUN ls -la /build/bin
 ---> Running in 10dab570c5a0
total 8
drwxr-xr-x 2 root root 4096 Aug 22 21:04 .
drwxr-xr-x 1 root root 4096 Aug 22 21:04 ..
-rw-r--r-- 1 root root    0 Aug 22 20:45 podinfo.yaml
Removing intermediate container 10dab570c5a0
 ---> b8f39097425e
Successfully built b8f39097425e
```

kaniko @ HEAD (`v1.14.0`):
```
aprindle@aprindle-ssd ~/kaniko  [main]./run_in_docker.sh /workspace/Dockerfile /usr/local/google/home/aprindle/kaniko-ctx-dir gcr.io/aprindle-test-cluster/kaniko-test:latest false |& tee ~/out.txt
INFO[0000] Retrieving image manifest ubuntu:latest      
INFO[0000] Retrieving image ubuntu:latest from registry index.docker.io 
INFO[0001] Built cross stage deps: map[]                
INFO[0001] Retrieving image manifest ubuntu:latest      
INFO[0001] Returning cached image manifest              
INFO[0001] Executing 0 build triggers                   
INFO[0001] Building stage 'ubuntu:latest' [idx: '0', base-idx: '-1'] 
INFO[0001] Unpacking rootfs as cmd RUN pwd requires it. 
INFO[0002] WORKDIR /build                               
INFO[0002] Cmd: workdir                                 
INFO[0002] Changed working directory to /build          
INFO[0002] Creating directory /build with uid -1 and gid -1 
INFO[0002] Taking snapshot of files...                  
INFO[0002] RUN pwd                                      
INFO[0002] Initializing snapshotter ...                 
INFO[0002] Taking snapshot of full filesystem...        
INFO[0002] Cmd: /bin/sh                                 
INFO[0002] Args: [-c pwd]                               
INFO[0002] Running: [/bin/sh -c pwd]                    
/build
INFO[0002] Taking snapshot of full filesystem...        
INFO[0002] No files were changed, appending empty layer to config. No layer added to image. 
INFO[0002] COPY podinfo.yaml bin/                       
INFO[0002] Taking snapshot of files...                  
INFO[0002] RUN ls -la /build/bin                        
INFO[0002] Cmd: /bin/sh                                 
INFO[0002] Args: [-c ls -la /build/bin]                 
INFO[0002] Running: [/bin/sh -c ls -la /build/bin]      
total 8
drwxr-xr-x 2 root   root  4096 Aug 22 22:01 .
drwxr-xr-x 3 root   root  4096 Aug 22 22:01 ..
-rw-r--r-- 1 386724 89939    0 Aug 22 22:01 podinfo.yaml
INFO[0002] Taking snapshot of full filesystem...        
INFO[0002] No files were changed, appending empty layer to config. No layer added to image. 
INFO[0002] Pushing image to gcr.io/aprindle-test-cluster/kaniko-test:latest 
INFO[0006] Pushed gcr.io/aprindle-test-cluster/kaniko-test@sha256:4219cbcdc367958375501ac3609dc5712bbbfbf80ec55185bf0d5c2a17780654 
```

Both built images put the `podinfo.yaml` at `/build/bin/podinfo.yaml`, kaniko no longer seems to put it at `/build/bin`
