### ISSUE TITLE
Missing ':' in substitution

### ISSUE THREAD

**Issue by z0mb1ek** [GoogleContainerTools/kaniko#1329] opened 2020-06-24 12:32 UTC
Hi. I try to build image with gcr.io/kaniko-project/executor:debug-v0.23.0 and it fail on command
```
RUN \
        ldd ${PREFIX}/bin/ffmpeg | grep opt/ffmpeg | cut -d ' ' -f 3 | xargs -i cp {} /usr/local/lib/ && \
        for lib in /usr/local/lib/*.so.*; do ln -s "${lib##*/}" "${lib%%.so.*}".so; done && \
        cp ${PREFIX}/bin/* /usr/local/bin/ && \
        cp -r ${PREFIX}/share/ffmpeg /usr/local/share/ && \
        LD_LIBRARY_PATH=/usr/local/lib ffmpeg -buildconf && \
        cp -r ${PREFIX}/include/libav* ${PREFIX}/include/libpostproc ${PREFIX}/include/libsw* /usr/local/include && \
        mkdir -p /usr/local/lib/pkgconfig && \
        for pc in ${PREFIX}/lib/pkgconfig/libav*.pc ${PREFIX}/lib/pkgconfig/libpostproc.pc ${PREFIX}/lib/pkgconfig/libsw*.pc; do \
          sed "s:${PREFIX}:/usr/local:g" <"$pc" >/usr/local/lib/pkgconfig/"${pc##*/}"; \
        done
```

with error
`error building image: error building stage: failed to optimize instructions: failed to process "RUN         ldd ${PREFIX}/bin/ffmpeg | grep opt/ffmpeg | cut -d ' ' -f 3 | xargs -i cp {} /usr/local/lib/ &&         for lib in /usr/local/lib/*.so.*; do ln -s \"${lib##*/}\" \"${lib%%.so.*}\".so; done &&         cp ${PREFIX}/bin/* /usr/local/bin/ &&         cp -r ${PREFIX}/share/ffmpeg /usr/local/share/ &&         LD_LIBRARY_PATH=/usr/local/lib ffmpeg -buildconf &&         cp -r ${PREFIX}/include/libav* ${PREFIX}/include/libpostproc ${PREFIX}/include/libsw* /usr/local/include &&         mkdir -p /usr/local/lib/pkgconfig &&         for pc in ${PREFIX}/lib/pkgconfig/libav*.pc ${PREFIX}/lib/pkgconfig/libpostproc.pc ${PREFIX}/lib/pkgconfig/libsw*.pc; do           sed \"s:${PREFIX}:/usr/local:g\" <\"$pc\" >/usr/local/lib/pkgconfig/\"${pc##*/}\";         done": missing ':' in substitution`

**Comment by Logrythmik** [comment] 2020-08-04 18:06
This is causing lots of issues for me too , with the simple RUN cmd:
`RUN for file in $(find common -iname *.csproj); do mkdir -p ${file%.csproj}/ && mv $file ${file%.csproj}/; done`

**Comment by dshiryaev-plesk** [comment] 2020-08-12 07:08
Does anyone know a workaround?

**Comment by dshiryaev-plesk** [comment] 2020-08-12 07:20
Same error for Docker "Official Image" for ruby: https://github.com/docker-library/ruby/blob/82eecb7596c3cb466dd87d4b0350d189a330b925/2.6/stretch/Dockerfile .

**Comment by dshiryaev-plesk** [comment] 2020-08-12 08:41
This is probably a duplicate of #1246

**Comment by tejal29** [comment] 2020-08-12 23:58
closing as dupe of #1246

**Closed** 2020-08-12 23:57 UTC
Labels: good first issue
