### ISSUE TITLE
new docker image v1.9.1 reports wrong version v1.9.0

### ISSUE THREAD

**Issue by khassel** [GoogleContainerTools/kaniko#2268] opened 2022-09-26 20:36 UTC
```bash
❯ docker run --rm gcr.io/kaniko-project/executor:v1.9.1 version
Kaniko version :  v1.9.0
```

**Comment by aaron-prindle** [comment] 2023-05-29 05:19
Dupe of https://github.com/GoogleContainerTools/kaniko/issues/2344, closing

**Closed by aaron-prindle** 2023-05-29 05:19 UTC
