### ISSUE TITLE
Kaniko Self Build

### ISSUE THREAD

**Issue by PhoenixMage** [GoogleContainerTools/kaniko#1136] opened 2020-03-16 02:17 UTC
Is it possible to self build Kaniko?

When I attempt to the resulting image doesnt work correctly. I believe it ends up with the /kaniko directory missing

**Comment by tejal29** [comment] 2020-03-17 06:30
that could be correct since /kaniko is whitelisted :)

**Comment by PhoenixMage** [comment] 2020-03-17 22:28
You are correct.

Good to know I am not going mad.

**Comment by saidrebhi** [comment] 2020-04-19 06:25
Any updates on this issue please?

**Comment by tejal29** [comment] 2020-05-07 18:37
@saidrebhi this is a little bit low on our radar unless we have a number of users pressing for this feature!

**Comment by dlakatos847** [comment] 2020-10-19 14:37
I faced this issue during building Kaniko image with Kaniko:
```
[INFO] Unpacking rootfs as cmd ADD tls-trust.pem /etc/tls-trust.pem requires it. 
error building image: error building stage: failed to get filesystem from image: removing whiteout kaniko/.docker/.wh..wh..opq: unlinkat 
```
The solution for me was not to mount `/kaniko/.docker` as a whole volume but to use K8S [`subPath`](https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath) to just mount the `/kaniko/.docker/config.json` file.

**Comment by aaron-prindle** [comment] 2023-07-04 00:18
Closing as a dupe of #407

**Closed by aaron-prindle** 2023-07-04 00:18 UTC
Labels: kind/question, priority/p3, area/behavior
