### ISSUE TITLE
Ownership of a directory is set to root when changing only a file in that directory

### ISSUE THREAD

**Issue by gilbsgilbs** [GoogleContainerTools/kaniko#1163] opened 2020-03-27 17:31 UTC
**Actual behavior**

Let's take the following tree:

```
.
└── [app  app ]  foo
    └── [app  app ]  bar

1 directory, 1 file
```

If I run the following commands:

```Dockerfile
USER app
RUN touch foo/bar
```

`foo` directory becomes owned by root in the forthcoming layers:

```
.
└── [root  root ]  foo
    └── [app  app ]  bar

1 directory, 1 file
```

This is inconsistent with Docker's behavior.

**Expected behavior**

I would expect the directory ownership to remain untouched in order to reflect the behavior from the Docker daemon.

**To Reproduce**

1. Create the following Dockerfile:
    ```Dockerfile
    FROM alpine:latest
    WORKDIR /app
    RUN addgroup -S app \
        && adduser -S app -G app \
        && mkdir foo \
        && touch foo/bar \
        && chown -R app:app foo/
    USER app
    RUN touch foo/bar
    CMD ["stat", "-c", "%U %G", "foo"]
    ```
2. Build it with docker daemon and run it (`docker build -t test_image . && docker run --rm -it test_image`). It should print `app app`.
3. Build it with kaniko and run it. It should print `root root`.

**Additional Information**

 - **Dockerfile:** See above.
 - **Build Context:** See above.
 - **Kaniko Image:** `debug-v0.19.0` (`sha256:0d0e34396f47ec6d5fd75aebb9772147a78d96ed2bbb16ec892bd178efdc8307`)
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [x] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by tstromberg** [comment] 2020-03-29 05:07
Thank you for the very detailed reproduction case! I should be able to get to solving it this week.

**Comment by gilbsgilbs** [comment] 2020-03-29 09:08
> I have literally no idea what is going on

From the information I have gathered while creating the repro, the problem seems to be that kaniko is not setting any tar header for directories. It looks like Docker needs them to not mess up ownership.

Here is what the `RUN touch foo/bar` layer look like when built using Docker:

```
$ tar --list --verbose --file=layer.tar
drwxr-xr-x 0/0               0 2020-03-28 16:06 app/
drwxr-xr-x 100/101           0 2020-03-28 16:06 app/foo/
-rw-r--r-- 100/101           0 2020-03-28 16:06 app/foo/bar
```

And when built using Kaniko:

```
$ tar --list --verbose --file=layer.tar
-rw-r--r-- 100/101           0 2020-03-28 16:18 app/foo/bar
```

Based on this repo, I've been able to make an integration test that fails:

```diff
diff --git a/integration/dockerfiles/Dockerfile_test_issue_1163 b/integration/dockerfiles/Dockerfile_test_issue_1163
new file mode 100644
index 00000000..0b9b1d86
--- /dev/null
+++ b/integration/dockerfiles/Dockerfile_test_issue_1163
@@ -0,0 +1,11 @@
+FROM alpine:latest
+WORKDIR /app
+RUN addgroup -S app \
+    && adduser -S app -G app \
+    && mkdir foo \
+    && touch foo/bar \
+    && chown -R app:app foo/
+USER app
+RUN touch foo/bar
+RUN rm -Rf foo/
+
```

I have a WIP locally that creates the directory headers. While this might fix the original repro, it is unfortunately not enough to make kaniko build this integration test successfully. Even if the created layer might be correctly handled in docker (this is yet to be confirmed), the ownership of `foo/` is incorrect within the kaniko image before executing the final command. I suspect this is due to how Kaniko initializes the FS before executing each command, but I haven't been able to dig any further yet.

Hope this helps.

**Comment by gilbsgilbs** [comment] 2020-03-29 16:19
@tstromberg That was it. Just submitted #1166 .

**Comment by gazal-k** [comment] 2020-04-05 07:33
I noticed the same issue. Thank you for the detailed bug report and the PR @gilbsgilbs

**Comment by GreeFine** [comment] 2020-04-14 16:20
I also got a related issue but somewhat different

```Dockerfile
FROM alpine

RUN touch /tmp/weird
RUN chmod +x /tmp/weird ## <- this line change the parent directory "/tmp" permissions
```
without chmod
```bash
docker run -it --rm --entrypoint sh greefine/testing:kaniko
/  ls -la /tmp/
total 8
drwxrwxrwt    1 root     root          4096 Apr 14 16:13 .
drwxr-xr-x    1 root     root          4096 Apr 14 16:13 ..
-rw-r--r--    1 root     root             0 Apr 14 16:13 weird
```

with chmod
```bash
docker run -it --rm --entrypoint sh greefine/testing:kaniko
/  ls -la /tmp
total 8
drwxr-xr-x    1 root     root          4096 Apr 14 16:00 .
drwxr-xr-x    1 root     root          4096 Apr 14 16:00 ..
-rwxr-xr-x    1 root     root             0 Apr 14 16:00 weird
```
Hope it can help resolving this issue, because it's not very practical for many of my projects where I do not the root user

**Closed** 2020-05-01 17:25 UTC
Labels: good first issue
