### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by ArsenyZorin** [GoogleContainerTools/kaniko#797] opened 2019-10-02 20:01 UTC
**Actual behavior**
Kaniko build fails in Gitlab CI.
Used image:
`image gcr.io/kaniko-project/executor:debug`

During build stage this error occures sometime:
```
INFO[0290] Downloading base image openjdk:12-alpine     
INFO[0291] Unpacking rootfs as cmd RUN adduser -D usr requires it. 
error building image: error building stage: read tcp 172.17.0.2:46282->104.18.123.25:443: read: connection reset by peer
```

**Expected behavior**
The container is built successfully.

**To Reproduce**
Gitlab CI configured as mentioned in Gitlab documentation
https://docs.gitlab.com/ee/ci/docker/using_kaniko.html

Gitlab Runner installed with helm
`image: gitlab/gitlab-runner:alpine-v12.1.0`

Gitlab CI file:
```
kaniko:
  image: gcr.io/kaniko-project/executor:debug
  script:
  - >
    echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":
    \"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" >
    /kaniko/.docker/config.json
  - /kaniko/executor --context ${CI_PROJECT_DIR} 
    --dockerfile ${CI_PROJECT_DIR}/Dockerfile 
    --destination ${CI_REGISTRY_IMAGE}:kaniko
```

**Additional Information**
 - Dockerfile 
```
FROM openjdk:12-alpine

COPY target/prog.jar /opt/prog/exec.jar

RUN adduser -D usr
USER usr
WORKDIR /home/usr

ENTRYPOINT ["java", "-jar", "/opt/prog/exec.jar"]
CMD [""]
```
 - Build Context
Directory with source code is used as build context
 - Kaniko Image (fully qualified with digest)
```
gcr.io/kaniko-project/executor:debug
```
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by tejal29** [comment] 2019-10-02 21:04
@ArsenyZorin you mentioned, it happens sometimes. Is this an intermittent error or happens always?

**Comment by ArsenyZorin** [comment] 2019-10-03 04:39
@tejal29 It happens at about 60% of all CI runs

**Comment by ataillefer** [comment] 2019-10-03 21:08
Hi, is your GitLab Runner using  a Kubernetes executor?
In which case you could be facing the bug described in the following blogs, that provide a workaround:
https://www.zenko.io/blog/solving-connection-reset-issue-in-kubernetes/
https://kubernetes.io/blog/2019/03/29/kube-proxy-subtleties-debugging-an-intermittent-connection-reset/

Also see
https://github.com/kubernetes/kubernetes/issues/74839
https://github.com/kubernetes/kubernetes/pull/74840

**Comment by tejal29** [comment] 2019-10-04 06:59
Thanks @ataillefer for the links! @ArsenyZorin Please try the solutions mentioned and let us know!

**Comment by ArsenyZorin** [comment] 2019-10-04 07:23
Thank you! I will take a look on all links

**Comment by tejal29** [comment] 2019-10-04 09:00
thanks. let us know.

**Comment by ArsenyZorin** [comment] 2019-11-06 06:29
Hello!

Sorry for so long response.
I've tested kaniko on different machines in my region (St.-Petersburg, Russia) there is the same problem `connection reset by peer`

When I tested in on Digital Ocean, on VM in Frankfurt, everything was fine!

So, I suppose, the problem is Russian network

**Comment by hlubek** [comment] 2019-12-05 14:34
We face the same issue in Gitlab CI. Testing our Kubernetes cluster (v1.15) with https://github.com/tcarmet/k8s-connection-reset shows no issues. Somehow this only occurs on larger layers and mostly be fixed by retrying the build.

**Comment by hlubek** [comment] 2019-12-06 14:43
> We face the same issue in Gitlab CI. Testing our Kubernetes cluster (v1.15) with https://github.com/tcarmet/k8s-connection-reset shows no issues. Somehow this only occurs on larger layers and mostly be fixed by retrying the build.

This seems not to be related to Kaniko. We (most certainly) also did not face the Kubernetes connection reset issue (but thx. for the informative links) - since we could not reproduce it.

What seems to help is the following annotations for the registry Nginx Ingress (taken from the Gitlab Helm chart):

```
nginx.ingress.kubernetes.io/proxy-body-size: "0"
nginx.ingress.kubernetes.io/proxy-read-timeout: "900"
nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
nginx.ingress.kubernetes.io/proxy-buffering: "off"
```

**Comment by tejal29** [comment] 2020-01-10 22:59
Thanks for following up @hlubek

**Closed by tejal29** 2020-01-10 22:59 UTC
Labels: area/dockerfile-command, priority/awaiting_evidence
