### ISSUE TITLE
pull mcr image failed

### ISSUE THREAD

**Issue by ViceIce** [GoogleContainerTools/kaniko#625] opened 2019-03-27 08:09 UTC
**Actual behavior**
Pulling an image from mcr.microsoft.com does not work

**Expected behavior**
Simply use images from mcr

**To Reproduce**
1. Build the following dockerfile

**Additional Information**
 - Dockerfile
```Dockerfile
FROM mcr.microsoft.com/dotnet/core/sdk:2.2-alpine
```
 - Kaniko Image (fully qualified with digest)
`gcr.io/kaniko-project/executor:debug@sha256:62bc2acb47775f717cd5e81076e46f2c552d0ae958cd6d300d42ff73892c19da`

**Comment by ViceIce** [comment] 2019-03-27 08:10
*Logs*
```
INFO[0000] Resolved base name mcr.microsoft.com/dotnet/core/sdk:2.2-alpine@sha256:7ed63433f04f9b7a56db36b038947af8f48b269c519b6d908f6f9ba9c70cb6e3 to mcr.microsoft.com/dotnet/core/sdk:2.2-alpine@sha256:7ed63433f04f9b7a56db36b038947af8f48b269c519b6d908f6f9ba9c70cb6e3 
INFO[0000] Resolved base name mcr.microsoft.com/dotnet/core/aspnet:2.2-alpine@sha256:ca791fd2ef2728717fd845e009c0072e093d551ed4b81ddb5a89a31d7eacf784 to mcr.microsoft.com/dotnet/core/aspnet:2.2-alpine@sha256:ca791fd2ef2728717fd845e009c0072e093d551ed4b81ddb5a89a31d7eacf784 
INFO[0000] Resolved base name mcr.microsoft.com/dotnet/core/sdk:2.2-alpine@sha256:7ed63433f04f9b7a56db36b038947af8f48b269c519b6d908f6f9ba9c70cb6e3 to mcr.microsoft.com/dotnet/core/sdk:2.2-alpine@sha256:7ed63433f04f9b7a56db36b038947af8f48b269c519b6d908f6f9ba9c70cb6e3 
INFO[0000] Resolved base name mcr.microsoft.com/dotnet/core/aspnet:2.2-alpine@sha256:ca791fd2ef2728717fd845e009c0072e093d551ed4b81ddb5a89a31d7eacf784 to mcr.microsoft.com/dotnet/core/aspnet:2.2-alpine@sha256:ca791fd2ef2728717fd845e009c0072e093d551ed4b81ddb5a89a31d7eacf784 
INFO[0000] Error while retrieving image from cache: getting file info: stat /cache/sha256:7ed63433f04f9b7a56db36b038947af8f48b269c519b6d908f6f9ba9c70cb6e3: no such file or directory 
INFO[0000] Downloading base image mcr.microsoft.com/dotnet/core/sdk:2.2-alpine@sha256:7ed63433f04f9b7a56db36b038947af8f48b269c519b6d908f6f9ba9c70cb6e3 
2019/03/27 07:49:50 No matching credentials were found, falling back on anonymous
error building image: Get https://mcr.microsoft.com/v2/: net/http: TLS handshake timeout
```

**Comment by kuznero** [comment] 2019-08-12 21:25
Same here, from Jenkins pipeline:

```
[37mDEBU[0m[0000] Copying file /home/jenkins/workspace/IAM_Service_master/Dockerfile to /kaniko/Dockerfile 
[36mINFO[0m[0000] Resolved base name mcr.microsoft.com/dotnet/core/aspnet:2.2.6-alpine3.9 to mcr.microsoft.com/dotnet/core/aspnet:2.2.6-alpine3.9 
[36mINFO[0m[0000] Resolved base name mcr.microsoft.com/dotnet/core/aspnet:2.2.6-alpine3.9 to mcr.microsoft.com/dotnet/core/aspnet:2.2.6-alpine3.9 
[36mINFO[0m[0000] Downloading base image mcr.microsoft.com/dotnet/core/aspnet:2.2.6-alpine3.9 
2019/08/12 21:22:16 No matching credentials were found, falling back on anonymous

[36mINFO[0m[0000] Error while retrieving image from cache: getting file info: stat /cache/sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855: no such file or directory 
[36mINFO[0m[0000] Downloading base image mcr.microsoft.com/dotnet/core/aspnet:2.2.6-alpine3.9 
2019/08/12 21:22:17 No matching credentials were found, falling back on anonymous
error building image: EOF
```

And here is an example of `Dockerfile` that it is trying to build:

```Dockerfile
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2.6-alpine3.9 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:2.2.401-alpine3.9 AS build
WORKDIR /src
COPY ["iam-service/iam-service.csproj", "iam-service/"]
RUN dotnet restore "iam-service/iam-service.csproj"
COPY . .
RUN dotnet build "iam-service/iam-service.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "iam-service/iam-service.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "iam-service.dll"] 
```

**Comment by kuznero** [comment] 2019-08-13 06:45
Workaround here is to re-tag images and push to hub.docker.com and change `Dockerfile` to point to a new images. Kaniko then can pull such images without any issues.

**Comment by donmccasland** [comment] 2019-09-20 20:21
Pulling from mcr.microsoft works for me in latest versions of Kaniko:
DEBU[0000] Getting source context from dir:///workspace/ 
DEBU[0000] Build context located at /workspace/         
DEBU[0000] Copying file /workspace/Dockerfile.bug625 to /kaniko/Dockerfile 
INFO[0000] Resolved base name mcr.microsoft.com/dotnet/core/aspnet:2.2.6-alpine3.9 to mcr.microsoft.com/dotnet/core/aspnet:2.2.6-alpine3.9 
INFO[0000] Resolved base name mcr.microsoft.com/dotnet/core/sdk:2.2.401-alpine3.9 to mcr.microsoft.com/dotnet/core/sdk:2.2.401-alpine3.9 
INFO[0000] Resolved base name build to build            
INFO[0000] Resolved base name base to base              
INFO[0000] Resolved base name mcr.microsoft.com/dotnet/core/aspnet:2.2.6-alpine3.9 to mcr.microsoft.com/dotnet/core/aspnet:2.2.6-alpine3.9 
INFO[0000] Resolved base name mcr.microsoft.com/dotnet/core/sdk:2.2.401-alpine3.9 to mcr.microsoft.com/dotnet/core/sdk:2.2.401-alpine3.9 
INFO[0000] Resolved base name build to build            
INFO[0000] Resolved base name base to base              
INFO[0000] Downloading base image mcr.microsoft.com/dotnet/core/aspnet:2.2.6-alpine3.9 
INFO[0001] Error while retrieving image from cache: getting file info: stat /cache/sha256:1ac68abdefd355b4cc52ce274ec5bebec1be820b1a58c069404d345abf035645: no such file or directory 
INFO[0001] Downloading base image mcr.microsoft.com/dotnet/core/aspnet:2.2.6-alpine3.9 
INFO[0003] Downloading base image mcr.microsoft.com/dotnet/core/sdk:2.2.401-alpine3.9 
INFO[0003] Error while retrieving image from cache: getting file info: stat /cache/sha256:d7c0ff807a79c83039f7e4f6a4eac75b6296a5024f572727ee331b969574f97c: no such file or directory 
INFO[0003] Downloading base image mcr.microsoft.com/dotnet/core/sdk:2.2.401-alpine3.9 
DEBU[0007] Resolved /app to /app                        
DEBU[0007] Resolved . to .                              
INFO[0007] Built cross stage deps: map[2:[/app]]        
INFO[0007] Downloading base image mcr.microsoft.com/dotnet/core/aspnet:2.2.6-alpine3.9 
INFO[0007] Error while retrieving image from cache: getting file info: stat /cache/sha256:1ac68abdefd355b4cc52ce274ec5bebec1be820b1a58c069404d345abf035645: no such file or directory 
INFO[0007] Downloading base image mcr.microsoft.com/dotnet/core/aspnet:2.2.6-alpine3.9 
INFO[0010] cmd: EXPOSE                                  
INFO[0010] Adding exposed port: 80/tcp                  
INFO[0010] cmd: EXPOSE                                  
INFO[0010] Adding exposed port: 443/tcp                 
INFO[0010] Skipping unpacking as no commands require it. 



Closing bug as non reproducible.  Reopen if you are continuing to have issues.

**Closed by donmccasland** 2019-09-20 20:21 UTC

**Comment by kuznero** [comment] 2019-09-21 18:54
@donmccasland could you please mention specific version that you have it working in?

**Comment by rachedanis** [comment] 2020-10-06 10:29
I'm facing the same issue, could you please reopen ?
