### ISSUE TITLE
v1.19.0-debug is causing build failures

### ISSUE THREAD

**Issue by todd-bush** [GoogleContainerTools/kaniko#2881] opened 2023-11-29 22:19 UTC
**Actual behavior**
Our builds started failing across all services about 45 mins ago, which is roughly when 1.19.0-debug was tagged.  Pinning to use 1.18.0-debug fixed all builds

**Additional Information**

We are running all builds in Jenkins and have been using executor:debug as the tag.  The builds push to ECR.  When the failures start, the logs looked like this:

` /kaniko/executor -f Dockerfile --registry-mirror bl-nexus01a.glh.local:8443 --insecure --skip-tls-verify --context /home/jenkins/agent/workspace/service-multi-branch_development --build-arg 'SSHKEY' --build-arg 'NEXUS_URL_BASE=10.40.22.12' '--destination=xxxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/servicename:tagname'
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "xxxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/customer-patient-service:20231129-571": POST https://xxxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/v2/service-name/blobs/uploads/: unexpected status code 401 Unauthorized: Not Authorized`

The logs did not show any attempt to build the service (like normal), it just failed with the above error.  I don't have much other information to provide.  Again, to get the build working again we just started using executor:v1.18.0-debug

 
 **Triage Notes for the Maintainers**

**Comment by aaron-prindle** [comment] 2023-11-29 22:39
Thanks for flagging this @todd-bush, closing as a dupe of https://github.com/GoogleContainerTools/kaniko/issues/2882.  Feel free to post there to continue the conversation related to this issue

**Closed by aaron-prindle** 2023-11-29 22:39 UTC
