### ISSUE TITLE
Dockerignore folders beginning with dot not ignored

### ISSUE THREAD

**Issue by Patrick-Remy** [GoogleContainerTools/kaniko#1486] opened 2020-11-09 20:54 UTC
**Actual behavior**
If the `.dockerignore` specifies a folder starting with a dot like `**/.git` and `.git` is a directory, the folder is printed to be ignored by kaniko, but effectively is instead included in the built image..  It needs `**/.git/**` so that all files will be ignored, but then every file is checked seperately, instead of skipping the whole tree (saw when enabling `-v=debug` flag, **it took 25s just for ignoring this full dir!**).

Just placing `.git` in `.dockerignore` seems to work and excludes the folder (at context rootdir), but doesn't match my needs. It also has the bug to walk through the full dir and prints/ignores each file which takes very long for huge repos or other folders like `psalm.cache`.

**Expected behavior**
Folder `.git` ignored without need for `**/<dirname>/**` in a performant way.

**To Reproduce**
1. Create a folder containing Dockerfile
```dockerfile
FROM alpine

WORKDIR /application
COPY . .
```
and .dockerignore
```dockerignore
**/.git
```

2. create folder and files
```sh
mkdir .git
touch .git/to-be-ignored
```

3. run `docker run --rm -it -v `pwd`:/build gcr.io/kaniko-project/executor:v1.3.0-debug --verbosity=debug --no-push --context /build`:

```
[...]
DEBU[0009] Copying file /build/.dockerignore to /application/.dockerignore 
DEBU[0009] Skipping excluded path: .git                 
DEBU[0009] /build/ found in .dockerignore, ignoring     
DEBU[0009] Copying file /build/.git/to-be-ignored to /application/.git/to-be-ignored 
DEBU[0009] Copying file /build/Dockerfile to /application/Dockerfile 
DEBU[0009] Copying file /build/test.sh to /application/test.sh 
INFO[0009] Taking snapshot of files...                  
DEBU[0009] Taking snapshot of files [/application/.dockerignore /application/.git/to-be-ignored /application/.git /application/Dockerfile /application/test.sh /application /] 
```

<details>
  <summary>Kaniko Full Logs</summary>
  
```
DEBU[0000] Copying file /build/Dockerfile to /kaniko/Dockerfile 
DEBU[0000] Skip resolving path /kaniko/Dockerfile       
DEBU[0000] Skip resolving path /build                   
DEBU[0000] Skip resolving path /cache                   
DEBU[0000] Skip resolving path                          
DEBU[0000] Skip resolving path                          
DEBU[0000] Skip resolving path                          
DEBU[0000] Built stage name to index map: map[]         
INFO[0000] Using dockerignore file: /build/.dockerignore 
INFO[0000] Retrieving image manifest alpine             
INFO[0000] Retrieving image alpine                      
DEBU[0001] No file found for cache key sha256:d7342993700f8cd7aba8496c2d0e57be0666e80b4c441925fc6f9361fa81d10e stat /cache/sha256:d7342993700f8cd7aba8496c2d0e57be0666e80b4c441925fc6f9361fa81d10e: no such file or directory 
DEBU[0001] Image alpine not found in cache              
INFO[0001] Retrieving image manifest alpine             
INFO[0001] Retrieving image alpine                      
INFO[0004] Built cross stage deps: map[]                
INFO[0004] Retrieving image manifest alpine             
INFO[0004] Retrieving image alpine                      
DEBU[0006] No file found for cache key sha256:d7342993700f8cd7aba8496c2d0e57be0666e80b4c441925fc6f9361fa81d10e stat /cache/sha256:d7342993700f8cd7aba8496c2d0e57be0666e80b4c441925fc6f9361fa81d10e: no such file or directory 
DEBU[0006] Image alpine not found in cache              
INFO[0006] Retrieving image manifest alpine             
INFO[0006] Retrieving image alpine                      
INFO[0008] Executing 0 build triggers                   
INFO[0008] Unpacking rootfs as cmd COPY . . requires it. 
DEBU[0008] Mounted directories: [{/kaniko false} {/etc/mtab false} {/tmp/apt-key-gpghome true} {/var/run false} {/proc false} {/dev false} {/dev/pts false} {/sys false} {/sys/fs/cgroup false} {/sys/fs/cgroup/cpuset false} {/sys/fs/cgroup/cpu false} {/sys/fs/cgroup/cpuacct false} {/sys/fs/cgroup/blkio false} {/sys/fs/cgroup/memory false} {/sys/fs/cgroup/devices false} {/sys/fs/cgroup/freezer false} {/sys/fs/cgroup/net_cls false} {/sys/fs/cgroup/perf_event false} {/sys/fs/cgroup/net_prio false} {/sys/fs/cgroup/hugetlb false} {/sys/fs/cgroup/pids false} {/sys/fs/cgroup/rdma false} {/sys/fs/cgroup/systemd false} {/dev/mqueue false} {/dev/shm false} {/build false} {/busybox false} {/etc/resolv.conf false} {/etc/hostname false} {/etc/hosts false} {/dev/console false} {/proc/bus false} {/proc/fs false} {/proc/irq false} {/proc/sys false} {/proc/sysrq-trigger false} {/proc/acpi false} {/proc/kcore false} {/proc/keys false} {/proc/timer_list false} {/proc/sched_debug false} {/sys/firmware false}] 
DEBU[0009] Not adding /dev because it is ignored        
DEBU[0009] Not adding /etc/hostname because it is ignored 
DEBU[0009] Not adding /etc/hosts because it is ignored  
DEBU[0009] Not adding /etc/mtab because it is ignored   
DEBU[0009] Not adding /proc because it is ignored       
DEBU[0009] Not adding /sys because it is ignored        
DEBU[0009] Not adding /var/run because it is ignored    
INFO[0009] WORKDIR /application                         
INFO[0009] cmd: workdir                                 
INFO[0009] Changed working directory to /application    
INFO[0009] Creating directory /application              
INFO[0009] Taking snapshot of files...                  
DEBU[0009] Taking snapshot of files [/application /]    
DEBU[0009] Resolved . to .                              
DEBU[0009] Resolved . to .                              
DEBU[0009] Using files from context: [/build]           
INFO[0009] COPY . .                                     
DEBU[0009] Resolved . to .                              
DEBU[0009] Resolved . to .                              
DEBU[0009] Getting files and contents at root /build/ for /build 
DEBU[0009] Copying file /build/.dockerignore to /application/.dockerignore 
DEBU[0009] Skipping excluded path: .git                 
DEBU[0009] /build/ found in .dockerignore, ignoring     
DEBU[0009] Copying file /build/.git/to-be-ignored to /application/.git/to-be-ignored 
DEBU[0009] Copying file /build/Dockerfile to /application/Dockerfile 
DEBU[0009] Copying file /build/test.sh to /application/test.sh 
INFO[0009] Taking snapshot of files...                  
DEBU[0009] Taking snapshot of files [/application/.dockerignore /application/.git/to-be-ignored /application/.git /application/Dockerfile /application/test.sh /application /] 
DEBU[0009] mapping stage idx 0 to digest sha256:df0e4be4851d807c154d496d7b62cb7360296811b238498e3379e0aaef59a76e 
DEBU[0009] mapping digest sha256:df0e4be4851d807c154d496d7b62cb7360296811b238498e3379e0aaef59a76e to cachekey  
INFO[0009] Skipping push to container registry due to --no-push flag
```
</details>

 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] docker ignores the folder completely</li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [x] bug exists with and without cache </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [x] bug exists in multi- and non-multistage </li></ul>|

**Comment by Patrick-Remy** [comment] 2020-11-12 21:57
I debugged at https://github.com/GoogleContainerTools/kaniko/blob/master/pkg/util/fs_util.go#L592-L601 `files` contains `[".git", ".git/to-be-ignored"]` and in the first loop `context.ExcludesFile(fullPath)` is true and it `continue`s. But the next loop copies the file as `.git/to-be-ignored` does not match the any pattern in `.gitignore`.
As there are no `!`-patterns, all files of the `.git` folder should be removed from the list. But that's difficult with that list/array data structure. A more recursive tree aproach would be much more performant, as directories can be skipped fully. That's also the aproach of moby/docker:

https://github.com/moby/moby/blob/d4b7b4b0a7465cb0bbdc3d4c2641c94524366532/pkg/archive/archive.go#L832-L862 that are responsible to ignore directories.

**Comment by geniass** [comment] 2021-04-16 11:00
@priyawadhwa @sharifelgamal @dlorenc I think this is a duplicate of #1396 

Not sure exactly who's responsible, as #1396 says its a bug in Moby

**Comment by annisat** [comment] 2022-01-14 09:12
My issue is simillar with a slight difference. I think I put it here.

My directory name to be ignore does not contains dot, but its subdirectory does. Then `**/<dir_name>/**` doesn't work either. docker-compose still tries to access files under its subdirectory, and, since it's a volume of another container and its owner is root in my case, OSError occurs and the build process stops.

**Comment by Panlq** [comment] 2022-01-24 07:24
found after debugging(kaniko-master):
the ** pattern does not include the root of the build context, 
but it works on the docker/docker/pkg/fileutils (moby/moby) (docker cli version 20.10.1)
does need to update the docker pkg to the latest?

**Comment by aaron-prindle** [comment] 2023-06-20 19:15
Can anyone in the thread here confirm if this is fixed in kaniko now?

**Comment by aaron-prindle** [comment] 2023-07-10 01:13
Going to close this as I believe it was fixed upstream

**Closed by aaron-prindle** 2023-07-10 01:13 UTC
Labels: priority/p2, needs-follow-up, possible-dupe, ok-to-close?, feat/dockerignore
