### ISSUE TITLE
USER command should not require user or group IDs to exist

### ISSUE THREAD

**Issue by chickeaterbanana** [GoogleContainerTools/kaniko#1778] opened 2021-10-19 14:01 UTC
**Actual behavior**
see also #477 

**Expected behavior**
docker image should be build.

**To Reproduce**
1. create a empty folder
2. create a file `test1` with following content:
```
FROM alpine
USER 1001
RUN echo 1
```
3. run `docker run --pull always --rm -it -v $PWD:/workspace gcr.io/kaniko-project/executor:latest --dockerfile=test1 --no-push --context=dir:///workspace`
4. run `docker run --pull always --rm -it -v $PWD:/workspace gcr.io/kaniko-project/executor:debug --dockerfile=test1 --no-push --context=dir:///workspace`

Results:
```
docker run --pull always --rm -it -v $PWD:/workspace gcr.io/kaniko-project/executor:debug --dockerfile=test1 --no-push --context=dir:///workspace                                              
Trying to pull gcr.io/kaniko-project/executor:debug...                                                                                                                                                             
Getting image source signatures                                                                                                                                                                                    
Copying blob fe2d5f51c3f2 skipped: already exists                                                                                                                                                                  
Copying blob d044254b2a54 skipped: already exists                                                                                                                                                                  
Copying blob ee2c784f1c11 skipped: already exists                                                                                                                                                                  
Copying blob 13e1a61a0623 skipped: already exists                                                                                                                                                                  
Copying blob 6566d8138b04 skipped: already exists                                                                                                                                                                  
Copying blob 981fc7edb8fd skipped: already exists                                                                                                                                                                  
Copying blob 3d8068545002 skipped: already exists                                                                                                                                                                  
Copying blob 8f137c16aecd skipped: already exists                                                                                                                                                                  
Copying blob 1e1b51c21c3c skipped: already exists                                                                                                                                                                  
Copying blob ddd1314b2f82 [--------------------------------------] 0.0b / 0.0b                                                                                                                                     
Copying config 7053f62a27 done                                                                                                                                                                                     
Writing manifest to image destination                                                                                                                                                                              
Storing signatures                                                                                                                                                                                                 
INFO[0000] Retrieving image manifest alpine                                                                                                                                                                        
INFO[0000] Retrieving image alpine from registry index.docker.io                                                                                                                                                   
INFO[0001] Built cross stage deps: map[]                                                                                                                                                                           
INFO[0001] Retrieving image manifest alpine                                                                                                                                                                        
INFO[0001] Returning cached image manifest                                                                                                                                                                         
INFO[0001] Executing 0 build triggers                                                                                                                                                                              
INFO[0001] Unpacking rootfs as cmd RUN echo 1 requires it.                                                                                                                                                         
INFO[0002] USER 1001                                                                                                                                                                                               
INFO[0002] cmd: USER                                                                                                                                                                                               
INFO[0002] RUN echo 1                                                                                                                                                                                              
INFO[0002] Taking snapshot of full filesystem...                                                                                                                                                                   
INFO[0003] cmd: /bin/sh                                                                                                                                                                                            
INFO[0003] args: [-c echo 1]                                                                                                                                                                                       
error building image: error building stage: failed to execute command: credentials: get uid/gid: user: unknown user 1001
```

**Additional Information**
 - Dockerfile 
```
FROM alpine
USER 1001
RUN echo 1
```
 - Build Context
 ```
ls
test1
```
 - Kaniko Image (fully qualified with digest)
gcr.io/kaniko-project/executor                            latest                    1c812ffa8ec1  5 months ago       78 MB
gcr.io/kaniko-project/executor                            debug                     7053f62a27a8  5 months ago       117 MB

 **Triage Notes for the Maintainers**
 

```
podman build -f test1
STEP 1/3: FROM alpine
STEP 2/3: USER 1001
--> ea606981a11
STEP 3/3: RUN echo 1
1
COMMIT
--> 4e089a5b588
4e089a5b5880156b1bb07a18cb42ffd2b35a76d17335445a05187d112e2a8f40
```
 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by aaron-prindle** [comment] 2023-07-15 00:17
Closing as a dupe of #477

**Closed by aaron-prindle** 2023-07-15 00:17 UTC
Labels: kind/bug, priority/p1, area/permissions, works-with-docker, differs-from-docker, possible-dupe, ok-to-close?, area/uid, kind/friction, categorized
