### ISSUE TITLE
Bind-mounting previous build-stages in multi-stage silently broken

### ISSUE THREAD

**Issue by Bigpet** [GoogleContainerTools/kaniko#2468] opened 2023-04-11 10:17 UTC
**Actual behavior**

Bind mounting build-stages in subsequent build-stages in multi-stage builds fails.

using `COPY --from=build /somedir /someotherdir/somedir` works in kaniko. But sometimes more sophisticated operations are needed to filter/copy files, in that case previous stages can be mounted into subsequent build-stages of a multi-stage build like so: `RUN --mount=type=bind,from=build,target=/bmount cp -rv /bmount/somedir /someotherdir`. This works in docker with ~~and without~~ buildkit, but the mounted folder is just empty in kaniko.

**Expected behavior**

The `RUN --mount=type=bind,from=prevstage` should mount the folder from the previous stage just like in docker

**To Reproduce**
1. try to build the listed Dockerfile with docker i.e. `cd /home/user/dev/kanikotest && docker build -t kanikotest .`
2. see it succeed
3. try to build the listed Dockerfile with kaniko i.e. `docker run -v "/home/user/dev/kanikotest/":/workspace gcr.io/kaniko-project/executor:latest --dockerfile "/workspace/Dockerfile" --destination "testimg" --context dir:///workspace/ --cache="false" --no-push`
4. see it fail
**Additional Information**
 - Dockerfile 
   Please provide either the Dockerfile you're trying to build or one that can reproduce this error.

```FROM alpine as build

RUN mkdir -p /somedir/subdir

RUN echo "testcontent" > /somedir/subdir/somefile

FROM alpine as run

RUN mkdir -p /someotherdir

RUN --mount=type=bind,from=build,target=/bmount \ 
    cp -rv /bmount/somedir /someotherdir

# COPY --from=build /somedir /someotherdir/somedir

RUN cat /someotherdir/somedir/subdir/somefile
```

 - Build Context

nothing extra needed

 - Kaniko Image (fully qualified with digest)
 
gcr.io/kaniko-project/executor@sha256:034f15e6fe235490e64a4173d02d0a41f61382450c314fffed9b8ca96dff66b2
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>| *1
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [x] </li></ul>| 
 
 *1 tried to get cache repo setup for 30mins, couldn't get it working

**Comment by Bigpet** [comment] 2023-04-11 11:12
possibly just a dupe of  https://github.com/GoogleContainerTools/kaniko/issues/1568 , but I don't have the knowledge to judge that.

**Comment by aaron-prindle** [comment] 2023-06-28 19:28
This is a dupe of #1568 where we are tracking adding bind mount support.  Feel free to +1 or continue the conversation on the issue there, thanks

**Closed by aaron-prindle** 2023-06-28 19:28 UTC
Labels: kind/bug, area/multi-stage builds, priority/p1, priority/p0, differs-from-docker, possible-dupe, issue/mount
